// Copyright (c) 2026 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Apache Software License 2.0 which is available at
// https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
// which is available at https://opensource.org/licenses/MIT.
//
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Applications whose services carry the C struct rosidl generates for a
//! ROS 2 message, serialized by the gateway's plain-struct translator.

use iceoryx2::prelude::*;
use rosidl_runtime_rs::{Message, RmwMessage};

/// Shared-memory payload for `geometry_msgs/msg/Twist`.
///
/// The `#[repr(C)]` `rmw` struct generated by `rosidl_generator_rs`,
/// with [`ZeroCopySend`] implemented so it can be used in an iceoryx2 service.
#[derive(Debug, Default, Clone)]
#[repr(transparent)]
pub struct Twist(pub ros_env::geometry_msgs::msg::rmw::Twist);

unsafe impl ZeroCopySend for Twist {
    unsafe fn type_name() -> &'static str {
        <<ros_env::geometry_msgs::msg::Twist as Message>::RmwMsg as RmwMessage>::TYPE_NAME
    }
}
