name: 'Save disk space'
description: 'Removes software packages and build artifacts that are not needed by the CI'
inputs:
  mode:
    description: "Defines which action to execute"
    required: true
  skip-remove-android-from-runner:
    description: "Defines if Android shall be removed in the pre step"
    required: false
    default: "false"
  skip-remove-dotnet-from-runner:
    description: "Defines if the Dotnet Framework shall be removed in the pre step"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
      - name: Remove unneeded software from runner
        if: ${{ inputs.mode == 'remove-unneeded-software-from-runner' }}
        shell: bash
        run: |
          sudo rm -rf /opt/ghc || true # Remove Haskell
          sudo rm -rf /usr/local/.ghcup || true # Remove Haskell
          sudo rm -rf /usr/share/swift || true 
          sudo rm -rf /usr/lib/google-cloud-sdk || true 
          sudo rm -rf /usr/local/share/chromium || true 
          sudo rm -rf /opt/microsoft/msedge || true
          sudo rm -rf /opt/google/chrome || true

          if [[ ${{ inputs.skip-remove-android-from-runner }} == 'false' ]]; then
            sudo rm -rf /usr/local/lib/android || true
          fi

          if [[ ${{ inputs.skip-remove-dotnet-from-runner }} == 'false' ]]; then
            sudo rm -rf /usr/share/dotnet || true
          fi


      - name: Cleanup build files from cargo target folder
        if: ${{ inputs.mode == 'cleanup-rust-build-files-from-cargo-target-folder' }}
        shell: bash
        run: |
          rm -rf ${{ github.workspace }}/target/{debug,release}/{deps,incremental}
          rm -rf ${{ github.workspace }}/target/*/{debug,release}/{deps,incremental} # Cleanup subfolders for target triples