# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

# automatically generated by the FlatBuffers compiler, do not modify

# pylint: skip-file

# namespace: Example

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class UnboundedData(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UnboundedData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUnboundedData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # UnboundedData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UnboundedData
    def Title(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UnboundedData
    def Entries(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Example.Entry import Entry

            obj = Entry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # UnboundedData
    def EntriesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UnboundedData
    def EntriesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0


def UnboundedDataStart(builder):
    builder.StartObject(2)


def Start(builder):
    UnboundedDataStart(builder)


def UnboundedDataAddTitle(builder, title):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(title), 0
    )


def AddTitle(builder, title):
    UnboundedDataAddTitle(builder, title)


def UnboundedDataAddEntries(builder, entries):
    builder.PrependUOffsetTRelativeSlot(
        1, flatbuffers.number_types.UOffsetTFlags.py_type(entries), 0
    )


def AddEntries(builder, entries):
    UnboundedDataAddEntries(builder, entries)


def UnboundedDataStartEntriesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartEntriesVector(builder, numElems):
    return UnboundedDataStartEntriesVector(builder, numElems)


def UnboundedDataCreateEntriesVector(builder, data):
    return builder.CreateVectorOfTables(data)


def CreateEntriesVector(builder, data):
    UnboundedDataCreateEntriesVector(builder, data)


def UnboundedDataEnd(builder):
    return builder.EndObject()


def End(builder):
    return UnboundedDataEnd(builder)
