# golangci-lint configuration for iceoryx2-go
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  # Include test files
  build-tags: []

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Additional linters
    - bodyclose       # Checks whether HTTP response body is closed successfully
    - contextcheck    # Checks for context.Context passing
    - dupl           # Tool for code clone detection
    - durationcheck   # Checks for two durations multiplied together
    - errname        # Checks that sentinel errors are prefixed with Err
    - errorlint      # Find problematic error wrapping
    - exhaustive     # Checks exhaustiveness of enum switch statements
    - exportloopref  # Checks for pointers to enclosing loop variables
    - gocognit       # Computes and checks cognitive complexity
    - goconst        # Finds repeated strings that could be replaced by a constant
    - gocritic       # Provides diagnostics that check for bugs, performance and style issues
    - gocyclo        # Computes and checks cyclomatic complexity
    - godot          # Checks if comments end in a period
    - gofmt          # Checks whether code was gofmt-ed
    - goimports      # In addition to fixing imports, goimports also formats your code
    - gosec          # Inspects source code for security problems
    - misspell       # Finds commonly misspelled English words in comments
    - nakedret       # Finds naked returns in functions greater than a specified function length
    - nilerr         # Finds the code that returns nil even if it checks that the error is not nil
    - nilnil         # Checks that there is no simultaneous return of nil error and an invalid value
    - noctx          # Finds sending http request without context.Context
    - prealloc       # Finds slice declarations that could potentially be preallocated
    - predeclared    # Finds code that shadows one of Go's predeclared identifiers
    - revive         # Fast, configurable, extensible, flexible, and beautiful linter
    - rowserrcheck   # Checks whether Err of rows is checked successfully
    - sqlclosecheck  # Checks that sql.Rows and sql.Stmt are closed
    - stylecheck     # Replacement for golint
    - testpackage    # Makes you use a separate _test package
    - tparallel      # Detects inappropriate usage of t.Parallel()
    - unconvert      # Remove unnecessary type conversions
    - unparam        # Reports unused function parameters
    - wastedassign   # Finds wasted assignment statements
    - whitespace     # Detection of leading and trailing whitespace

  disable:
    - depguard       # We don't restrict imports
    - funlen         # Function length is checked by cognitive complexity instead
    - gochecknoinits # We use init() for cgo setup
    - gochecknoglobals # We need globals for cgo
    - lll            # Line length is not enforced
    - nlreturn       # Too strict
    - wrapcheck      # We have our own error wrapping strategy
    - wsl            # Too strict about whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (*os.File).Close
      - (io.Closer).Close

  govet:
    settings:
      printf:
        funcs:
          - (github.com/eclipse-iceoryx/iceoryx2/iceoryx2-go/pkg/iceoryx2).Errorf

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  goconst:
    min-len: 3
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - hugeParam      # We pass structs by value intentionally
      - rangeValCopy   # We copy loop values intentionally in some cases

  goimports:
    local-prefixes: github.com/eclipse-iceoryx/iceoryx2

  gosec:
    excludes:
      - G103 # Use of unsafe calls - required for cgo
      - G115 # Integer overflow conversion - we handle this appropriately

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: indent-error-flow
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: var-declaration
      - name: var-naming

  stylecheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016"]
    # ST1000: Package comments
    # ST1003: Underscore in package name (iceoryx2 has underscores)
    # ST1016: Receiver names not using the right style

  testpackage:
    skip-regexp: "_internal_test\\.go"

  unparam:
    check-exported: false

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - gocognit
        - gocyclo
        
    # cgo files need unsafe
    - path: \.go
      text: "use of unsafe"
      linters:
        - gosec

    # Allow fmt.Sprintf in error construction
    - text: "fmt.Sprintf"
      linters:
        - perfsprint

  max-issues-per-linter: 50
  max-same-issues: 10
  new: false
