# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

# automatically generated by the FlatBuffers compiler, do not modify

# pylint: skip-file

# namespace: Example

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class DataProps(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DataProps()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDataProps(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # DataProps
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DataProps
    def ReceivedEntriesLen(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Uint64Flags, o + self._tab.Pos
            )
        return 0


def DataPropsStart(builder):
    builder.StartObject(1)


def Start(builder):
    DataPropsStart(builder)


def DataPropsAddReceivedEntriesLen(builder, receivedEntriesLen):
    builder.PrependUint64Slot(0, receivedEntriesLen, 0)


def AddReceivedEntriesLen(builder, receivedEntriesLen):
    DataPropsAddReceivedEntriesLen(builder, receivedEntriesLen)


def DataPropsEnd(builder):
    return builder.EndObject()


def End(builder):
    return DataPropsEnd(builder)
