#!/usr/bin/expect
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

#### Common Setup

set REPO_ROOT [exec git rev-parse --show-toplevel]
cd ${REPO_ROOT}

source ${REPO_ROOT}/internal/end-to-end-testing/common.exp

#### Test Setup

exec cargo build --manifest-path integrations/ros2/Cargo.toml \
    --bin iox2-link-gateway-ros2 2>@1

#### Test

set timeout 30

set env(IOX2_LOG_LEVEL) trace
spawn cargo run --manifest-path integrations/ros2/Cargo.toml \
    --bin iox2-link-gateway-ros2 -- --translator PlainStruct --monitor
set id_gateway $spawn_id
unset env(IOX2_LOG_LEVEL)
expect_output_from $id_gateway "Gateway started"

spawn ros2 run demo_nodes_iceoryx2 \
    prefix_mapping_plain_struct_translator_publisher
set id_publisher $spawn_id
expect_output_from $id_publisher "send:"

spawn ros2 topic echo /cmd_vel
set id_echo $spawn_id

#### Test Assertion

expect_output_from $id_gateway "Opened PublishSubscribe bridge of ros2://topics/cmd_vel"
expect_output_from $id_gateway "PublishSubscribe bridge of ros2://topics/cmd_vel moved"

expect_output_from $id_echo "x: 0.5"

#### Shutdown

send -i $id_echo $SIGINT
expect -i $id_echo eof

send -i $id_publisher $SIGINT
expect -i $id_publisher eof

send -i $id_gateway $SIGINT
expect_output_from $id_gateway "Gateway stopped"
expect -i $id_gateway eof

show_test_passed
