#!/usr/bin/expect
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

#### Common Setup

set REPO_ROOT [exec git rev-parse --show-toplevel]
cd ${REPO_ROOT}

source ${REPO_ROOT}/internal/end-to-end-testing/common.exp

#### Test

set timeout 30

spawn ros2 run demo_nodes_iceoryx2 subscriber
set id_subscriber $spawn_id

expect_output_from $id_subscriber "waiting on Counter"

spawn ros2 run demo_nodes_iceoryx2 publisher
set id_publisher $spawn_id

#### Test Assertion

expect_output_from $id_publisher "send 1"
expect_output_from $id_subscriber "received 1"

#### Shutdown

send -i $id_publisher $SIGINT
expect -i $id_publisher eof

send -i $id_subscriber $SIGINT
expect -i $id_subscriber eof

show_test_passed
