#!/usr/bin/expect
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

#### Common Setup

set REPO_ROOT [exec git rev-parse --show-toplevel]
cd ${REPO_ROOT}

source examples/cross-language-end-to-end-tests/common.exp

#### Test Setup

set timeout 10

spawn python examples/python/request_response/server.py
set id_server $spawn_id

spawn python examples/python/request_response/client.py

#### Test Assertion

expect_output_from $id_server "Server ready to receive requests!"
expect_output "send request 2"
expect_output "received response"
expect_output "send request 3"
expect_output "received response"

show_test_passed
