#
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

#### Define Colors

set C_RED "\033\[1;31m"
set C_GREEN "\033\[1;32m"
set C_YELLOW "\033\[1;33m"
set C_BLUE "\033\[1;34m"
set C_OFF "\033\[0m"

#### Helper Functions

proc handle_timeout { EXPECTED_OUTPUT } {
    global C_RED C_YELLOW C_OFF
    puts "${C_RED}Test failed!${C_OFF}"
    puts "${C_YELLOW}Expected string:${C_OFF} ${EXPECTED_OUTPUT}"
    puts "${C_YELLOW}Actual:${C_OFF} \[timed out\]"
    exit 1
}

proc handle_end_of_file { EXPECTED_OUTPUT } {
    global C_RED C_YELLOW C_OFF
    puts "${C_RED}Test failed!${C_OFF}"
    puts "${C_YELLOW}Received 'eof' instead of:${C_OFF} ${EXPECTED_OUTPUT}"
    exit 1
}

proc expect_output { EXPECTED_OUTPUT } {
    expect {
        "${EXPECTED_OUTPUT}" { }
        timeout { handle_timeout ${EXPECTED_OUTPUT} }
        eof { handle_end_of_file ${EXPECTED_OUTPUT} }
    }
}

proc expect_output_from { SPAWN_ID EXPECTED_OUTPUT } {
    expect {
        -i ${SPAWN_ID} "${EXPECTED_OUTPUT}" { }
        timeout { handle_timeout ${EXPECTED_OUTPUT} }
        eof { handle_end_of_file ${EXPECTED_OUTPUT} }
    }
}

proc show_test_passed { } {
    global C_GREEN C_OFF
    puts "${C_GREEN}Test passed!${C_OFF}"
}
