#### Define Colors

set C_RED "\033\[1;31m"
set C_GREEN "\033\[1;32m"
set C_YELLOW "\033\[1;33m"
set C_BLUE "\033\[1;34m"
set C_OFF "\033\[0m"

#### Helper Functions

proc handle_timeout { EXPECTED_OUTPUT } {
    global C_RED C_YELLOW C_OFF
    puts "${C_RED}Test failed!${C_OFF}"
    puts "${C_YELLOW}Expected string:${C_OFF} ${EXPECTED_OUTPUT}"
    puts "${C_YELLOW}Actual:${C_OFF} \[timed out\]"
    exit 1
}

proc expect_output { EXPECTED_OUTPUT } {
    expect {
        "${EXPECTED_OUTPUT}" { }
        timeout { handle_timeout ${EXPECTED_OUTPUT} }
    }
}

proc show_test_passed { } {
    global C_GREEN C_OFF
    puts "${C_GREEN}Test passed!${C_OFF}"
}
