#!/usr/bin/expect

#### Common Setup

set REPO_ROOT [exec git rev-parse --show-toplevel]
cd ${REPO_ROOT}

source examples/cross-language-end-to-end-tests/common.exp

#### Test Setup

set timeout 10

spawn target/ffi/build/examples/c/publish_subscribe_cross_language/example_c_cross_language_publisher

spawn target/ffi/build/examples/cxx/publish_subscribe_cross_language/example_cxx_publish_subscribe_cross_language_subscriber

#### Test Assertion

expect_output "received: TransmissionData { x: 3, y: 9, funky: 2436.36 }*"

show_test_passed
