#!/usr/bin/expect

#### Common Setup

set REPO_ROOT [exec git rev-parse --show-toplevel]
cd ${REPO_ROOT}

source examples/cross-language-end-to-end-tests/common.exp

#### Test Setup

set timeout 10

spawn target/ffi/build/examples/cxx/event/example_cxx_event_notifier

spawn cargo run --example event_listener

#### Test Assertion

expect_output "event was triggered with id: TriggerId(3)"

show_test_passed
