#!/usr/bin/expect

#### Common Setup

set REPO_ROOT [exec git rev-parse --show-toplevel]
cd ${REPO_ROOT}

source examples/cross-language-end-to-end-tests/common.exp

#### Test Setup

set timeout 10

spawn target/ffi/build/examples/cxx/request_response/example_cxx_request_response_server

spawn target/ffi/build/examples/c/request_response/example_c_request_response_client

set EXPECTED_OUTPUT "received response 3: *"

#### Test Assertion

expect_output "received response 3: *"

show_test_passed
