name: 'Set Build Flags'
description: 'Sets flags for Cargo and CMake'
inputs:
  profile:
    description: "Build profile {dev;dev-fast-build;release;release-fast-build}"
    required: true
outputs:
  c-binding-artifacts-folder-name:
    description: "The name of the folder with the C binding artifacts"
    value: ${{ steps.set-build-flags.outputs.c-binding-artifacts-folder-name}}
  cmake-build-type:
    description: "CMake Build Type"
    value: ${{ steps.set-build-flags.outputs.cmake-build-type }}
  cmake-build-config:
    description: "CMake Build Config"
    value: ${{ steps.set-build-flags.outputs.cmake-build-config }}
runs:
  using: "composite"
  steps:
      - name: Set Build Flags
        id: set-build-flags
        shell: bash
        run: |
          C_BINDING_ARTIFACTS_FOLDER_NAME="${{ inputs.profile }}"
          CMAKE_BUILD_TYPE=""
          CMAKE_BUILD_CONFIG=""

          if [[ ${{ inputs.profile }} == dev ]]; then
            C_BINDING_ARTIFACTS_FOLDER_NAME="debug"
          fi

          if [[ ${{ inputs.profile }} == release* ]]; then
            CMAKE_BUILD_TYPE="-DCMAKE_BUILD_TYPE=Release"
            CMAKE_BUILD_CONFIG="--config Release"
          fi
          if [[ ${{ inputs.profile }} == dev* ]]; then
            CMAKE_BUILD_TYPE="-DCMAKE_BUILD_TYPE=Debug"
            CMAKE_BUILD_CONFIG="--config Debug"
          fi

          echo "c-binding-artifacts-folder-name=$(echo $C_BINDING_ARTIFACTS_FOLDER_NAME)" >> $GITHUB_OUTPUT
          echo "cmake-build-type=$(echo $CMAKE_BUILD_TYPE)" >> $GITHUB_OUTPUT
          echo "cmake-build-config=$(echo $CMAKE_BUILD_CONFIG)" >> $GITHUB_OUTPUT

          echo "Cargo profile: ${{ inputs.profile }}"
          echo "CMake build type: ${CMAKE_BUILD_TYPE}"
          echo "C binding artifacts folder name: ${C_BINDING_ARTIFACTS_FOLDER_NAME}"
