// automatically generated by the FlatBuffers compiler, do not modify
// @generated

extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod example {

extern crate alloc;

pub enum DataPropsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DataProps<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for DataProps<'a> {
  type Inner = DataProps<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> DataProps<'a> {
  pub const VT_RECEIVED_ENTRIES_LEN: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    DataProps { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DataPropsArgs
  ) -> ::flatbuffers::WIPOffset<DataProps<'bldr>> {
    let mut builder = DataPropsBuilder::new(_fbb);
    builder.add_received_entries_len(args.received_entries_len);
    builder.finish()
  }


  #[inline]
  pub fn received_entries_len(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(DataProps::VT_RECEIVED_ENTRIES_LEN, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for DataProps<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("received_entries_len", Self::VT_RECEIVED_ENTRIES_LEN, false)?
     .finish();
    Ok(())
  }
}
pub struct DataPropsArgs {
    pub received_entries_len: u64,
}
impl<'a> Default for DataPropsArgs {
  #[inline]
  fn default() -> Self {
    DataPropsArgs {
      received_entries_len: 0,
    }
  }
}

pub struct DataPropsBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DataPropsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_received_entries_len(&mut self, received_entries_len: u64) {
    self.fbb_.push_slot::<u64>(DataProps::VT_RECEIVED_ENTRIES_LEN, received_entries_len, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> DataPropsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DataPropsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<DataProps<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for DataProps<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("DataProps");
      ds.field("received_entries_len", &self.received_entries_len());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `DataProps`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_data_props_unchecked`.
pub fn root_as_data_props(buf: &[u8]) -> Result<DataProps<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<DataProps>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `DataProps` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_data_props_unchecked`.
pub fn size_prefixed_root_as_data_props(buf: &[u8]) -> Result<DataProps<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<DataProps>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `DataProps` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_data_props_unchecked`.
pub fn root_as_data_props_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<DataProps<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<DataProps<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `DataProps` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_data_props_unchecked`.
pub fn size_prefixed_root_as_data_props_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<DataProps<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<DataProps<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a DataProps and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `DataProps`.
pub unsafe fn root_as_data_props_unchecked(buf: &[u8]) -> DataProps<'_> {
  unsafe { ::flatbuffers::root_unchecked::<DataProps>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed DataProps and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `DataProps`.
pub unsafe fn size_prefixed_root_as_data_props_unchecked(buf: &[u8]) -> DataProps<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<DataProps>(buf) }
}
#[inline]
pub fn finish_data_props_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<DataProps<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_data_props_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<DataProps<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod Example

