// automatically generated by the FlatBuffers compiler, do not modify
// @generated

extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod example {

extern crate alloc;

pub enum EntryOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Entry<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Entry<'a> {
  type Inner = Entry<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Entry<'a> {
  pub const VT_DATA_1: ::flatbuffers::VOffsetT = 4;
  pub const VT_DATA_2: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Entry { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args EntryArgs
  ) -> ::flatbuffers::WIPOffset<Entry<'bldr>> {
    let mut builder = EntryBuilder::new(_fbb);
    builder.add_data_2(args.data_2);
    builder.add_data_1(args.data_1);
    builder.finish()
  }


  #[inline]
  pub fn data_1(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Entry::VT_DATA_1, Some(0)).unwrap()}
  }
  #[inline]
  pub fn data_2(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Entry::VT_DATA_2, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Entry<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<i32>("data_1", Self::VT_DATA_1, false)?
     .visit_field::<u64>("data_2", Self::VT_DATA_2, false)?
     .finish();
    Ok(())
  }
}
pub struct EntryArgs {
    pub data_1: i32,
    pub data_2: u64,
}
impl<'a> Default for EntryArgs {
  #[inline]
  fn default() -> Self {
    EntryArgs {
      data_1: 0,
      data_2: 0,
    }
  }
}

pub struct EntryBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> EntryBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_data_1(&mut self, data_1: i32) {
    self.fbb_.push_slot::<i32>(Entry::VT_DATA_1, data_1, 0);
  }
  #[inline]
  pub fn add_data_2(&mut self, data_2: u64) {
    self.fbb_.push_slot::<u64>(Entry::VT_DATA_2, data_2, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> EntryBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    EntryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Entry<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Entry<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Entry");
      ds.field("data_1", &self.data_1());
      ds.field("data_2", &self.data_2());
      ds.finish()
  }
}
pub enum UnboundedDataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct UnboundedData<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for UnboundedData<'a> {
  type Inner = UnboundedData<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> UnboundedData<'a> {
  pub const VT_TITLE: ::flatbuffers::VOffsetT = 4;
  pub const VT_ENTRIES: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    UnboundedData { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args UnboundedDataArgs<'args>
  ) -> ::flatbuffers::WIPOffset<UnboundedData<'bldr>> {
    let mut builder = UnboundedDataBuilder::new(_fbb);
    if let Some(x) = args.entries { builder.add_entries(x); }
    if let Some(x) = args.title { builder.add_title(x); }
    builder.finish()
  }


  #[inline]
  pub fn title(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(UnboundedData::VT_TITLE, None)}
  }
  #[inline]
  pub fn entries(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Entry<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Entry>>>>(UnboundedData::VT_ENTRIES, None)}
  }
}

impl ::flatbuffers::Verifiable for UnboundedData<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("title", Self::VT_TITLE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Entry>>>>("entries", Self::VT_ENTRIES, false)?
     .finish();
    Ok(())
  }
}
pub struct UnboundedDataArgs<'a> {
    pub title: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub entries: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Entry<'a>>>>>,
}
impl<'a> Default for UnboundedDataArgs<'a> {
  #[inline]
  fn default() -> Self {
    UnboundedDataArgs {
      title: None,
      entries: None,
    }
  }
}

pub struct UnboundedDataBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> UnboundedDataBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_title(&mut self, title: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(UnboundedData::VT_TITLE, title);
  }
  #[inline]
  pub fn add_entries(&mut self, entries: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Entry<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(UnboundedData::VT_ENTRIES, entries);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> UnboundedDataBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    UnboundedDataBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<UnboundedData<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for UnboundedData<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("UnboundedData");
      ds.field("title", &self.title());
      ds.field("entries", &self.entries());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `UnboundedData`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_unbounded_data_unchecked`.
pub fn root_as_unbounded_data(buf: &[u8]) -> Result<UnboundedData<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<UnboundedData>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `UnboundedData` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_unbounded_data_unchecked`.
pub fn size_prefixed_root_as_unbounded_data(buf: &[u8]) -> Result<UnboundedData<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<UnboundedData>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `UnboundedData` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_unbounded_data_unchecked`.
pub fn root_as_unbounded_data_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<UnboundedData<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<UnboundedData<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `UnboundedData` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_unbounded_data_unchecked`.
pub fn size_prefixed_root_as_unbounded_data_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<UnboundedData<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<UnboundedData<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a UnboundedData and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `UnboundedData`.
pub unsafe fn root_as_unbounded_data_unchecked(buf: &[u8]) -> UnboundedData<'_> {
  unsafe { ::flatbuffers::root_unchecked::<UnboundedData>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed UnboundedData and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `UnboundedData`.
pub unsafe fn size_prefixed_root_as_unbounded_data_unchecked(buf: &[u8]) -> UnboundedData<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<UnboundedData>(buf) }
}
#[inline]
pub fn finish_unbounded_data_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<UnboundedData<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_unbounded_data_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<UnboundedData<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod Example

