#!/usr/bin/expect
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

#### Common Setup

set REPO_ROOT [exec git rev-parse --show-toplevel]
cd ${REPO_ROOT}

source ${REPO_ROOT}/internal/end-to-end-testing/common.exp

set env(IOX2_FLATBUFFER_SCHEMA_PATH) ${REPO_ROOT}/examples/cxx/flatbuffer_publish_subscribe/src

set publisher_binary target/ff/cc/build/examples/cxx/flatbuffer_publish_subscribe/example_cxx_flatbuffer_publish_subscribe_publisher

if {![file executable $publisher_binary]} {
    puts stdout "Flatbuffer example does not exist"
    show_test_skipped
    exit 0
}

#### Test Setup

set timeout 10

spawn target/ff/cc/build/examples/cxx/flatbuffer_publish_subscribe/example_cxx_flatbuffer_publish_subscribe_publisher
set id_publisher $spawn_id

spawn target/ff/cc/build/examples/cxx/flatbuffer_publish_subscribe/example_cxx_flatbuffer_publish_subscribe_subscriber

#### Test Assertion

expect_output_from $id_publisher "Send sample*"
expect_output "Entry 0: data_1=5, data_2=7"

show_test_passed
