[package]
name = "iceoryx2-integrations-ros2-tunnel-cli"
description = "iceoryx2-integrations: ros2 tunnel CLI"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[[bin]]
name = "iox2-tunnel-ros2"
path = "src/main.rs"

[dependencies]
iceoryx2-integrations-ros2-tunnel-backend = { workspace = true }

iceoryx2 = { workspace = true }
iceoryx2-cli = { workspace = true }
iceoryx2-log = { workspace = true }
iceoryx2-services-tunnel = { workspace = true }
iceoryx2-services-tunnel-backend = { workspace = true }

anyhow = { workspace = true }
better-panic = { workspace = true }
clap = { workspace = true }
human-panic = { workspace = true }
toml = { workspace = true }
