# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

constraint_setting(
    name = "requires_feature_flatbuffers",
    visibility = ["//visibility:private"],
)

constraint_value(
    name = "requires_feature_flatbuffers_on",
    constraint_setting = ":requires_feature_flatbuffers",
    visibility = ["//visibility:private"],
)

cc_binary(
    name = "example_cxx_flatbuffer_request_response_client",
    srcs = [
        "src/client.cpp",
        "src/transmission_data.hpp",
    ],
    deps = [
        "//:iceoryx2-bb-cxx",
        "//:iceoryx2-cxx-static",
    ],
)

cc_binary(
    name = "example_cxx_flatbuffer_request_response_server",
    srcs = [
        "src/server.cpp",
        "src/transmission_data.hpp",
    ],
    deps = [
        "//:iceoryx2-bb-cxx",
        "//:iceoryx2-cxx-static",
    ],
)
