#!/usr/bin/expect
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

#### Common Setup

set REPO_ROOT [exec git rev-parse --show-toplevel]
cd ${REPO_ROOT}

set env(IOX2_FLATBUFFER_SCHEMA_PATH) ${REPO_ROOT}/examples/cxx/flatbuffer_request_response/src

source ${REPO_ROOT}/internal/end-to-end-testing/common.exp

#### Test Setup

set timeout 10

spawn target/ff/cc/build/examples/cxx/flatbuffer_request_response/example_cxx_flatbuffer_request_response_server
set id_server $spawn_id

spawn target/ff/cc/build/examples/cxx/flatbuffer_request_response/example_cxx_flatbuffer_request_response_client

#### Test Assertion

expect_output_from $id_server "Server ready to receive requests!"
expect_output "Received response: 12"

show_test_passed
