// Copyright (c) 2026 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Apache Software License 2.0 which is available at
// https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
// which is available at https://opensource.org/licenses/MIT.
//
// SPDX-License-Identifier: Apache-2.0 OR MIT

extern crate alloc;

use iceoryx2_bb_testing_macros::conformance_tests;

#[allow(clippy::module_inception)]
#[conformance_tests]
pub mod service_request_response_flatbuffer {
    use alloc::vec;
    use iceoryx2::service::builder::request_response::{
        RequestResponseCreateError, RequestResponseOpenError,
    };
    use iceoryx2::service::{Service, marker::Flatbuffer};
    use iceoryx2_bb_posix::config::TEST_DIRECTORY;
    use iceoryx2_bb_posix::testing::*;
    use iceoryx2_bb_testing::assert_that;
    use iceoryx2_bb_testing_macros::conformance_test;
    use iceoryx2_cal::static_storage::StaticStorageView;
    use iceoryx2_testing::*;

    //////////////////////////////
    // START: generated by flatc
    //////////////////////////////
    #[allow(unused_imports, dead_code)]
    pub mod example {

        extern crate alloc;

        pub enum DataPropsOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct DataProps<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for DataProps<'a> {
            type Inner = DataProps<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> DataProps<'a> {
            pub const VT_RECEIVED_ENTRIES_LEN: ::flatbuffers::VOffsetT = 4;

            #[inline]
            /// # Safety
            ///  code generated
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                DataProps { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args DataPropsArgs,
            ) -> ::flatbuffers::WIPOffset<DataProps<'bldr>> {
                let mut builder = DataPropsBuilder::new(_fbb);
                builder.add_received_entries_len(args.received_entries_len);
                builder.finish()
            }

            #[inline]
            pub fn received_entries_len(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u64>(DataProps::VT_RECEIVED_ENTRIES_LEN, Some(0))
                        .unwrap()
                }
            }
        }

        impl ::flatbuffers::Verifiable for DataProps<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<u64>(
                        "received_entries_len",
                        Self::VT_RECEIVED_ENTRIES_LEN,
                        false,
                    )?
                    .finish();
                Ok(())
            }
        }
        pub struct DataPropsArgs {
            pub received_entries_len: u64,
        }
        impl Default for DataPropsArgs {
            #[inline]
            fn default() -> Self {
                DataPropsArgs {
                    received_entries_len: 0,
                }
            }
        }

        pub struct DataPropsBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DataPropsBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_received_entries_len(&mut self, received_entries_len: u64) {
                self.fbb_.push_slot::<u64>(
                    DataProps::VT_RECEIVED_ENTRIES_LEN,
                    received_entries_len,
                    0,
                );
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> DataPropsBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                DataPropsBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<DataProps<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for DataProps<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("DataProps");
                ds.field("received_entries_len", &self.received_entries_len());
                ds.finish()
            }
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a `DataProps`
        /// and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_data_props_unchecked`.
        pub fn root_as_data_props(
            buf: &[u8],
        ) -> Result<DataProps<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root::<DataProps>(buf)
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a size prefixed
        /// `DataProps` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `size_prefixed_root_as_data_props_unchecked`.
        pub fn size_prefixed_root_as_data_props(
            buf: &[u8],
        ) -> Result<DataProps<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root::<DataProps>(buf)
        }
        #[inline]
        /// Verifies, with the given options, that a buffer of bytes
        /// contains a `DataProps` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_data_props_unchecked`.
        pub fn root_as_data_props_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<DataProps<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root_with_opts::<DataProps<'b>>(opts, buf)
        }
        #[inline]
        /// Verifies, with the given verifier options, that a buffer of
        /// bytes contains a size prefixed `DataProps` and returns
        /// it. Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_data_props_unchecked`.
        pub fn size_prefixed_root_as_data_props_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<DataProps<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root_with_opts::<DataProps<'b>>(opts, buf)
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a DataProps and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid `DataProps`.
        pub unsafe fn root_as_data_props_unchecked(buf: &[u8]) -> DataProps<'_> {
            unsafe { ::flatbuffers::root_unchecked::<DataProps>(buf) }
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a size prefixed DataProps and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid size prefixed `DataProps`.
        pub unsafe fn size_prefixed_root_as_data_props_unchecked(buf: &[u8]) -> DataProps<'_> {
            unsafe { ::flatbuffers::size_prefixed_root_unchecked::<DataProps>(buf) }
        }
        #[inline]
        pub fn finish_data_props_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<DataProps<'a>>,
        ) {
            fbb.finish(root, None);
        }

        #[inline]
        pub fn finish_size_prefixed_data_props_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<DataProps<'a>>,
        ) {
            fbb.finish_size_prefixed(root, None);
        }

        pub enum EntryOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct Entry<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for Entry<'a> {
            type Inner = Entry<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> Entry<'a> {
            pub const VT_DATA_1: ::flatbuffers::VOffsetT = 4;
            pub const VT_DATA_2: ::flatbuffers::VOffsetT = 6;

            #[inline]
            unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                Entry { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args EntryArgs,
            ) -> ::flatbuffers::WIPOffset<Entry<'bldr>> {
                let mut builder = EntryBuilder::new(_fbb);
                builder.add_data_2(args.data_2);
                builder.add_data_1(args.data_1);
                builder.finish()
            }

            #[inline]
            pub fn data_1(&self) -> i32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<i32>(Entry::VT_DATA_1, Some(0)).unwrap() }
            }
            #[inline]
            pub fn data_2(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u64>(Entry::VT_DATA_2, Some(0)).unwrap() }
            }
        }

        impl ::flatbuffers::Verifiable for Entry<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<i32>("data_1", Self::VT_DATA_1, false)?
                    .visit_field::<u64>("data_2", Self::VT_DATA_2, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct EntryArgs {
            pub data_1: i32,
            pub data_2: u64,
        }
        impl Default for EntryArgs {
            #[inline]
            fn default() -> Self {
                EntryArgs {
                    data_1: 0,
                    data_2: 0,
                }
            }
        }

        pub struct EntryBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> EntryBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_data_1(&mut self, data_1: i32) {
                self.fbb_.push_slot::<i32>(Entry::VT_DATA_1, data_1, 0);
            }
            #[inline]
            pub fn add_data_2(&mut self, data_2: u64) {
                self.fbb_.push_slot::<u64>(Entry::VT_DATA_2, data_2, 0);
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> EntryBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                EntryBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<Entry<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for Entry<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("Entry");
                ds.field("data_1", &self.data_1());
                ds.field("data_2", &self.data_2());
                ds.finish()
            }
        }
        pub enum UnboundedDataOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct UnboundedData<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for UnboundedData<'a> {
            type Inner = UnboundedData<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> UnboundedData<'a> {
            pub const VT_TITLE: ::flatbuffers::VOffsetT = 4;
            pub const VT_ENTRIES: ::flatbuffers::VOffsetT = 6;

            #[inline]
            unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                UnboundedData { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args UnboundedDataArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<UnboundedData<'bldr>> {
                let mut builder = UnboundedDataBuilder::new(_fbb);
                if let Some(x) = args.entries {
                    builder.add_entries(x);
                }
                if let Some(x) = args.title {
                    builder.add_title(x);
                }
                builder.finish()
            }

            #[inline]
            pub fn title(&self) -> Option<&'a str> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<::flatbuffers::ForwardsUOffset<&str>>(UnboundedData::VT_TITLE, None)
                }
            }
            #[inline]
            pub fn entries(
                &self,
            ) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Entry<'a>>>>
            {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<::flatbuffers::ForwardsUOffset<
                        ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Entry>>,
                    >>(UnboundedData::VT_ENTRIES, None)
                }
            }
        }

        impl ::flatbuffers::Verifiable for UnboundedData<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                        "title",
                        Self::VT_TITLE,
                        false,
                    )?
                    .visit_field::<::flatbuffers::ForwardsUOffset<
                        ::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Entry>>,
                    >>("entries", Self::VT_ENTRIES, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct UnboundedDataArgs<'a> {
            pub title: Option<::flatbuffers::WIPOffset<&'a str>>,
            pub entries: Option<
                ::flatbuffers::WIPOffset<
                    ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Entry<'a>>>,
                >,
            >,
        }
        impl<'a> Default for UnboundedDataArgs<'a> {
            #[inline]
            fn default() -> Self {
                UnboundedDataArgs {
                    title: None,
                    entries: None,
                }
            }
        }

        pub struct UnboundedDataBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> UnboundedDataBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_title(&mut self, title: ::flatbuffers::WIPOffset<&'b str>) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    UnboundedData::VT_TITLE,
                    title,
                );
            }
            #[inline]
            pub fn add_entries(
                &mut self,
                entries: ::flatbuffers::WIPOffset<
                    ::flatbuffers::Vector<'b, ::flatbuffers::ForwardsUOffset<Entry<'b>>>,
                >,
            ) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    UnboundedData::VT_ENTRIES,
                    entries,
                );
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> UnboundedDataBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                UnboundedDataBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<UnboundedData<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for UnboundedData<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("UnboundedData");
                ds.field("title", &self.title());
                ds.field("entries", &self.entries());
                ds.finish()
            }
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a `UnboundedData`
        /// and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_unbounded_data_unchecked`.
        pub fn root_as_unbounded_data(
            buf: &[u8],
        ) -> Result<UnboundedData<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root::<UnboundedData>(buf)
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a size prefixed
        /// `UnboundedData` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `size_prefixed_root_as_unbounded_data_unchecked`.
        pub fn size_prefixed_root_as_unbounded_data(
            buf: &[u8],
        ) -> Result<UnboundedData<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root::<UnboundedData>(buf)
        }
        #[inline]
        /// Verifies, with the given options, that a buffer of bytes
        /// contains a `UnboundedData` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_unbounded_data_unchecked`.
        pub fn root_as_unbounded_data_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<UnboundedData<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root_with_opts::<UnboundedData<'b>>(opts, buf)
        }
        #[inline]
        /// Verifies, with the given verifier options, that a buffer of
        /// bytes contains a size prefixed `UnboundedData` and returns
        /// it. Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_unbounded_data_unchecked`.
        pub fn size_prefixed_root_as_unbounded_data_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<UnboundedData<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root_with_opts::<UnboundedData<'b>>(opts, buf)
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a UnboundedData and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid `UnboundedData`.
        pub unsafe fn root_as_unbounded_data_unchecked(buf: &[u8]) -> UnboundedData<'_> {
            unsafe { ::flatbuffers::root_unchecked::<UnboundedData>(buf) }
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a size prefixed UnboundedData and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid size prefixed `UnboundedData`.
        pub unsafe fn size_prefixed_root_as_unbounded_data_unchecked(
            buf: &[u8],
        ) -> UnboundedData<'_> {
            unsafe { ::flatbuffers::size_prefixed_root_unchecked::<UnboundedData>(buf) }
        }
        #[inline]
        pub fn finish_unbounded_data_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<UnboundedData<'a>>,
        ) {
            fbb.finish(root, None);
        }

        #[inline]
        pub fn finish_size_prefixed_unbounded_data_buffer<
            'a,
            'b,
            A: ::flatbuffers::Allocator + 'a,
        >(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<UnboundedData<'a>>,
        ) {
            fbb.finish_size_prefixed(root, None);
        }
    }
    //////////////////////////////
    // END: generated by flatc
    //////////////////////////////

    const DATA_PROPS_SCHEMA: &str = "
        namespace Example;

        table DataProps {
            received_entries_len: uint64;
        }

        root_type DataProps;
    ";

    const UNBOUND_DATA_SCHEMA: &str = "
        namespace Example;

        table Entry {
            data_1: int32;
            data_2: uint64;
        }

        table UnboundedData {
            title: string;
            entries: [Entry];
        }

        root_type UnboundedData;
    ";

    #[conformance_test]
    pub fn create_fails_when_no_schema_file_is_available_for_request<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let service_name = generate_service_name();
        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, u64>()
            .create();

        assert_that!(sut.err(), eq Some(RequestResponseCreateError::UnableToAcquireTypeDefinition));
    }

    #[conformance_test]
    pub fn create_fails_when_no_schema_file_is_available_for_response<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let service_name = generate_service_name();
        let sut = node
            .service_builder(&service_name)
            .request_response::<u64, Flatbuffer<u64>>()
            .create();

        assert_that!(sut.err(), eq Some(RequestResponseCreateError::UnableToAcquireTypeDefinition));
    }

    #[conformance_test]
    pub fn create_succeeds_with_request_schema_file<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let schema_file = create_file_with_content(UNBOUND_DATA_SCHEMA);

        let service_name = generate_service_name();
        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, u64>()
            .request_flatbuffer_schema_path(schema_file.path().unwrap())
            .create();

        assert_that!(sut, is_ok);
    }

    #[conformance_test]
    pub fn create_succeeds_with_response_schema_file<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let schema_file = create_file_with_content(UNBOUND_DATA_SCHEMA);

        let service_name = generate_service_name();
        let sut = node
            .service_builder(&service_name)
            .request_response::<u64, Flatbuffer<u64>>()
            .response_flatbuffer_schema_path(schema_file.path().unwrap())
            .create();

        assert_that!(sut, is_ok);
    }

    #[conformance_test]
    pub fn create_succeeds_with_request_and_response_schema_file<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let schema_file = create_file_with_content(UNBOUND_DATA_SCHEMA);

        let service_name = generate_service_name();
        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, Flatbuffer<u64>>()
            .request_flatbuffer_schema_path(schema_file.path().unwrap())
            .response_flatbuffer_schema_path(schema_file.path().unwrap())
            .create();

        assert_that!(sut, is_ok);
    }

    #[conformance_test]
    pub fn open_fails_when_no_request_schema_file_is_available<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let schema_file = create_file_with_content(UNBOUND_DATA_SCHEMA);

        let service_name = generate_service_name();
        let _sut_create = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, u64>()
            .request_flatbuffer_schema_path(schema_file.path().unwrap())
            .create();

        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, u64>()
            .open();

        assert_that!(sut.err(), eq Some(RequestResponseOpenError::UnableToAcquireTypeDefinition));
    }

    #[conformance_test]
    pub fn open_fails_when_no_response_schema_file_is_available<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let schema_file = create_file_with_content(UNBOUND_DATA_SCHEMA);

        let service_name = generate_service_name();
        let _sut_create = node
            .service_builder(&service_name)
            .request_response::<u64, Flatbuffer<u64>>()
            .response_flatbuffer_schema_path(schema_file.path().unwrap())
            .create();

        let sut = node
            .service_builder(&service_name)
            .request_response::<u64, Flatbuffer<u64>>()
            .open();

        assert_that!(sut.err(), eq Some(RequestResponseOpenError::UnableToAcquireTypeDefinition));
    }

    #[conformance_test]
    pub fn open_fails_when_request_schema_file_is_not_the_same<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let schema_file = create_file_with_content(UNBOUND_DATA_SCHEMA);
        let alt_schema_file = create_file_with_content(DATA_PROPS_SCHEMA);

        let service_name = generate_service_name();
        let _sut_create = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, Flatbuffer<u64>>()
            .request_flatbuffer_schema_path(schema_file.path().unwrap())
            .response_flatbuffer_schema_path(schema_file.path().unwrap())
            .create();

        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, Flatbuffer<u64>>()
            .request_flatbuffer_schema_path(alt_schema_file.path().unwrap())
            .response_flatbuffer_schema_path(schema_file.path().unwrap())
            .open();

        assert_that!(sut.err(), eq Some(RequestResponseOpenError::IncompatibleRequestOrResponseType));
    }

    #[conformance_test]
    pub fn open_fails_when_response_schema_file_is_not_the_same<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let schema_file = create_file_with_content(UNBOUND_DATA_SCHEMA);
        let alt_schema_file = create_file_with_content(DATA_PROPS_SCHEMA);

        let service_name = generate_service_name();
        let _sut_create = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, Flatbuffer<u64>>()
            .request_flatbuffer_schema_path(schema_file.path().unwrap())
            .response_flatbuffer_schema_path(schema_file.path().unwrap())
            .create();

        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, Flatbuffer<u64>>()
            .request_flatbuffer_schema_path(schema_file.path().unwrap())
            .response_flatbuffer_schema_path(alt_schema_file.path().unwrap())
            .open();

        assert_that!(sut.err(), eq Some(RequestResponseOpenError::IncompatibleRequestOrResponseType));
    }

    #[conformance_test]
    pub fn open_succeeds_when_schema_content_is_identical<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let schema_file = create_file_with_content(UNBOUND_DATA_SCHEMA);
        let alt_schema_file = create_file_with_content(DATA_PROPS_SCHEMA);

        let service_name = generate_service_name();
        let _sut_create = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, Flatbuffer<u64>>()
            .request_flatbuffer_schema_path(schema_file.path().unwrap())
            .response_flatbuffer_schema_path(alt_schema_file.path().unwrap())
            .create();

        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, Flatbuffer<u64>>()
            .request_flatbuffer_schema_path(schema_file.path().unwrap())
            .response_flatbuffer_schema_path(alt_schema_file.path().unwrap())
            .open();

        assert_that!(sut, is_ok);
    }

    #[conformance_test]
    pub fn schema_path_lookup_works_when_creating_a_service<Sut: Service>() {
        let mut test = Test::<Sut>::new();
        test.config_mut().global.service.flatbuffer_schema_path = Some(TEST_DIRECTORY);
        let node = test.create_node();
        let _schema_file = create_file_with_content_at(UNBOUND_DATA_SCHEMA, "unbounded_data.fbs");
        let _alt_schema_file = create_file_with_content_at(DATA_PROPS_SCHEMA, "data_props.fbs");

        let service_name = generate_service_name();
        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<example::UnboundedData>, Flatbuffer<example::DataProps>>(
            )
            .create();

        assert_that!(sut, is_ok);
    }

    #[conformance_test]
    pub fn schema_path_lookup_works_when_opening_a_service<Sut: Service>() {
        let mut test = Test::<Sut>::new();
        test.config_mut().global.service.flatbuffer_schema_path = Some(TEST_DIRECTORY);
        let node = test.create_node();
        let _schema_file = create_file_with_content_at(UNBOUND_DATA_SCHEMA, "unbounded_data.fbs");
        let _alt_schema_file = create_file_with_content_at(DATA_PROPS_SCHEMA, "data_props.fbs");

        let service_name = generate_service_name();
        let _sut_create = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<example::UnboundedData>, Flatbuffer<example::DataProps>>(
            )
            .create();

        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<example::UnboundedData>, Flatbuffer<example::DataProps>>(
            )
            .open();

        assert_that!(sut, is_ok);
    }

    #[conformance_test]
    pub fn request_schema_is_identical_to_origin<Sut: Service>() {
        let mut test = Test::<Sut>::new();
        test.config_mut().global.service.flatbuffer_schema_path = Some(TEST_DIRECTORY);
        let node = test.create_node();
        let schema_file = create_file_with_content_at(UNBOUND_DATA_SCHEMA, "unbounded_data.fbs");
        let alt_schema_file = create_file_with_content_at(DATA_PROPS_SCHEMA, "data_props.fbs");

        let service_name = generate_service_name();
        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, Flatbuffer<u64>>()
            .request_flatbuffer_schema_path(schema_file.path().unwrap())
            .response_flatbuffer_schema_path(alt_schema_file.path().unwrap())
            .create()
            .unwrap();

        let type_definition = sut.request_type_definition().unwrap();

        assert_that!(type_definition.len(), eq UNBOUND_DATA_SCHEMA.len() as u64);
        let mut buffer = vec![0u8; UNBOUND_DATA_SCHEMA.len()];
        type_definition.read(&mut buffer).unwrap();

        assert_that!(UNBOUND_DATA_SCHEMA.as_bytes(), eq buffer.as_slice());
    }

    #[conformance_test]
    pub fn response_schema_is_identical_to_origin<Sut: Service>() {
        let mut test = Test::<Sut>::new();
        test.config_mut().global.service.flatbuffer_schema_path = Some(TEST_DIRECTORY);
        let node = test.create_node();
        let schema_file = create_file_with_content_at(UNBOUND_DATA_SCHEMA, "unbounded_data.fbs");
        let alt_schema_file = create_file_with_content_at(DATA_PROPS_SCHEMA, "data_props.fbs");

        let service_name = generate_service_name();
        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, Flatbuffer<u64>>()
            .request_flatbuffer_schema_path(schema_file.path().unwrap())
            .response_flatbuffer_schema_path(alt_schema_file.path().unwrap())
            .create()
            .unwrap();

        let type_definition = sut.response_type_definition().unwrap();

        assert_that!(type_definition.len(), eq DATA_PROPS_SCHEMA.len() as u64);
        let mut buffer = vec![0u8; DATA_PROPS_SCHEMA.len()];
        type_definition.read(&mut buffer).unwrap();

        assert_that!(DATA_PROPS_SCHEMA.as_bytes(), eq buffer.as_slice());
    }
}
