// Copyright (c) 2026 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Apache Software License 2.0 which is available at
// https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
// which is available at https://opensource.org/licenses/MIT.
//
// SPDX-License-Identifier: Apache-2.0 OR MIT

extern crate alloc;

use iceoryx2_bb_testing_macros::conformance_tests;

#[allow(clippy::module_inception)]
#[conformance_tests]
pub mod service_publish_subscribe_flatbuffer {
    use alloc::vec;
    use flatbuffers::{FlatBufferBuilder, WIPOffset};
    use iceoryx2::sample_mut_uninit::FlatbufferMemory;
    use iceoryx2::service::builder::publish_subscribe::{
        PublishSubscribeCreateError, PublishSubscribeOpenError,
    };
    use iceoryx2::service::{Service, marker::Flatbuffer};
    use iceoryx2_bb_elementary::allocation_strategy::AllocationStrategy;
    use iceoryx2_bb_posix::file::{CreationMode, File, FileBuilder};
    use iceoryx2_bb_posix::testing::*;
    use iceoryx2_bb_testing::assert_that;
    use iceoryx2_bb_testing_macros::conformance_test;
    use iceoryx2_cal::static_storage::StaticStorage;
    use iceoryx2_testing::*;

    //////////////////////////////
    // START: generated by flatc
    //////////////////////////////
    pub enum EntryOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct Entry<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for Entry<'a> {
        type Inner = Entry<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> Entry<'a> {
        pub const VT_DATA_1: ::flatbuffers::VOffsetT = 4;
        pub const VT_DATA_2: ::flatbuffers::VOffsetT = 6;

        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args EntryArgs,
        ) -> ::flatbuffers::WIPOffset<Entry<'bldr>> {
            let mut builder = EntryBuilder::new(_fbb);
            builder.add_data_2(args.data_2);
            builder.add_data_1(args.data_1);
            builder.finish()
        }

        #[inline]
        pub fn data_1(&self) -> i32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<i32>(Entry::VT_DATA_1, Some(0)).unwrap() }
        }
        #[inline]
        pub fn data_2(&self) -> u64 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<u64>(Entry::VT_DATA_2, Some(0)).unwrap() }
        }
    }

    impl ::flatbuffers::Verifiable for Entry<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<i32>("data_1", Self::VT_DATA_1, false)?
                .visit_field::<u64>("data_2", Self::VT_DATA_2, false)?
                .finish();
            Ok(())
        }
    }
    pub struct EntryArgs {
        pub data_1: i32,
        pub data_2: u64,
    }
    impl Default for EntryArgs {
        #[inline]
        fn default() -> Self {
            EntryArgs {
                data_1: 0,
                data_2: 0,
            }
        }
    }

    pub struct EntryBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> EntryBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_data_1(&mut self, data_1: i32) {
            self.fbb_.push_slot::<i32>(Entry::VT_DATA_1, data_1, 0);
        }
        #[inline]
        pub fn add_data_2(&mut self, data_2: u64) {
            self.fbb_.push_slot::<u64>(Entry::VT_DATA_2, data_2, 0);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> EntryBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            EntryBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<Entry<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for Entry<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("Entry");
            ds.field("data_1", &self.data_1());
            ds.field("data_2", &self.data_2());
            ds.finish()
        }
    }
    pub enum UnboundedDataOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct UnboundedData<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for UnboundedData<'a> {
        type Inner = UnboundedData<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> UnboundedData<'a> {
        pub const VT_TITLE: ::flatbuffers::VOffsetT = 4;
        pub const VT_ENTRIES: ::flatbuffers::VOffsetT = 6;

        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args UnboundedDataArgs<'args>,
        ) -> ::flatbuffers::WIPOffset<UnboundedData<'bldr>> {
            let mut builder = UnboundedDataBuilder::new(_fbb);
            if let Some(x) = args.entries {
                builder.add_entries(x);
            }
            if let Some(x) = args.title {
                builder.add_title(x);
            }
            builder.finish()
        }

        #[inline]
        pub fn title(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<::flatbuffers::ForwardsUOffset<&str>>(UnboundedData::VT_TITLE, None)
            }
        }
        #[inline]
        pub fn entries(
            &self,
        ) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Entry<'a>>>> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab.get::<::flatbuffers::ForwardsUOffset<
                    ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Entry>>,
                >>(UnboundedData::VT_ENTRIES, None)
            }
        }
    }

    impl ::flatbuffers::Verifiable for UnboundedData<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                    "title",
                    Self::VT_TITLE,
                    false,
                )?
                .visit_field::<::flatbuffers::ForwardsUOffset<
                    ::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Entry>>,
                >>("entries", Self::VT_ENTRIES, false)?
                .finish();
            Ok(())
        }
    }
    pub struct UnboundedDataArgs<'a> {
        pub title: Option<::flatbuffers::WIPOffset<&'a str>>,
        pub entries: Option<
            ::flatbuffers::WIPOffset<
                ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Entry<'a>>>,
            >,
        >,
    }
    impl<'a> Default for UnboundedDataArgs<'a> {
        #[inline]
        fn default() -> Self {
            UnboundedDataArgs {
                title: None,
                entries: None,
            }
        }
    }

    pub struct UnboundedDataBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> UnboundedDataBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_title(&mut self, title: ::flatbuffers::WIPOffset<&'b str>) {
            self.fbb_
                .push_slot_always::<::flatbuffers::WIPOffset<_>>(UnboundedData::VT_TITLE, title);
        }
        #[inline]
        pub fn add_entries(
            &mut self,
            entries: ::flatbuffers::WIPOffset<
                ::flatbuffers::Vector<'b, ::flatbuffers::ForwardsUOffset<Entry<'b>>>,
            >,
        ) {
            self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                UnboundedData::VT_ENTRIES,
                entries,
            );
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> UnboundedDataBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            UnboundedDataBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<UnboundedData<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for UnboundedData<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("UnboundedData");
            ds.field("title", &self.title());
            ds.field("entries", &self.entries());
            ds.finish()
        }
    }
    #[inline]
    /// Verifies that a buffer of bytes contains a `UnboundedData`
    /// and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_unbounded_data_unchecked`.
    pub fn root_as_unbounded_data(
        buf: &[u8],
    ) -> Result<UnboundedData<'_>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::root::<UnboundedData>(buf)
    }
    #[inline]
    /// Verifies that a buffer of bytes contains a size prefixed
    /// `UnboundedData` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `size_prefixed_root_as_unbounded_data_unchecked`.
    pub fn size_prefixed_root_as_unbounded_data(
        buf: &[u8],
    ) -> Result<UnboundedData<'_>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::size_prefixed_root::<UnboundedData>(buf)
    }
    #[inline]
    /// Verifies, with the given options, that a buffer of bytes
    /// contains a `UnboundedData` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_unbounded_data_unchecked`.
    pub fn root_as_unbounded_data_with_opts<'b, 'o>(
        opts: &'o ::flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<UnboundedData<'b>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::root_with_opts::<UnboundedData<'b>>(opts, buf)
    }
    #[inline]
    /// Verifies, with the given verifier options, that a buffer of
    /// bytes contains a size prefixed `UnboundedData` and returns
    /// it. Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_unbounded_data_unchecked`.
    pub fn size_prefixed_root_as_unbounded_data_with_opts<'b, 'o>(
        opts: &'o ::flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<UnboundedData<'b>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::size_prefixed_root_with_opts::<UnboundedData<'b>>(opts, buf)
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a UnboundedData and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid `UnboundedData`.
    pub unsafe fn root_as_unbounded_data_unchecked(buf: &[u8]) -> UnboundedData<'_> {
        unsafe { ::flatbuffers::root_unchecked::<UnboundedData>(buf) }
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a size prefixed UnboundedData and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid size prefixed `UnboundedData`.
    pub unsafe fn size_prefixed_root_as_unbounded_data_unchecked(buf: &[u8]) -> UnboundedData<'_> {
        unsafe { ::flatbuffers::size_prefixed_root_unchecked::<UnboundedData>(buf) }
    }
    #[inline]
    pub fn finish_unbounded_data_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
        fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        root: ::flatbuffers::WIPOffset<UnboundedData<'a>>,
    ) {
        fbb.finish(root, None);
    }

    #[inline]
    pub fn finish_size_prefixed_unbounded_data_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
        fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        root: ::flatbuffers::WIPOffset<UnboundedData<'a>>,
    ) {
        fbb.finish_size_prefixed(root, None);
    }
    //////////////////////////////
    // END: generated by flatc
    //////////////////////////////

    const SCHEMA: &str = "
        namespace Example;

        table Entry {
            data_1: int32;
            data_2: uint64;
        }

        table UnboundedData {
            title: string;
            entries: [Entry];
        }

        root_type UnboundedData;
    ";

    const ALT_SCHEMA: &str = "
        namespace Example;

        table BoundedData {
            data_1: int32;
        }

        root_type BoundedData;
    ";

    fn create_schema_file(schema: &str) -> File {
        let schema_file = generate_file_path();
        let mut file = FileBuilder::new(&schema_file)
            .creation_mode(CreationMode::PurgeAndCreate)
            .create()
            .unwrap();
        file.acquire_ownership();
        file.write(schema.as_bytes()).unwrap();
        file
    }

    #[conformance_test]
    pub fn create_fails_when_no_schema_file_is_available<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let service_name = generate_service_name();
        let sut = node
            .service_builder(&service_name)
            .publish_subscribe::<Flatbuffer<u64>>()
            .create();

        assert_that!(sut.err(), eq Some(PublishSubscribeCreateError::UnableToAcquireTypeDefinition));
    }

    #[conformance_test]
    pub fn create_succeeds_with_schema_file<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let schema_file = create_schema_file(SCHEMA);

        let service_name = generate_service_name();
        let sut = node
            .service_builder(&service_name)
            .publish_subscribe::<Flatbuffer<u64>>()
            .flatbuffer_schema_path(schema_file.path().unwrap())
            .create();

        assert_that!(sut, is_ok);
    }

    #[conformance_test]
    pub fn open_fails_when_no_schema_file_is_available<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let service_name = generate_service_name();
        let schema_file = create_schema_file(SCHEMA);

        let _sut_create = node
            .service_builder(&service_name)
            .publish_subscribe::<Flatbuffer<u64>>()
            .flatbuffer_schema_path(schema_file.path().unwrap())
            .create();

        let sut = node
            .service_builder(&service_name)
            .publish_subscribe::<Flatbuffer<u64>>()
            .open();

        assert_that!(sut.err(), eq Some(PublishSubscribeOpenError::UnableToAcquireTypeDefinition));
    }

    #[conformance_test]
    pub fn open_fails_when_schema_is_not_the_same<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let service_name = generate_service_name();
        let schema_file = create_schema_file(SCHEMA);
        let alt_schema_file = create_schema_file(ALT_SCHEMA);

        let _sut_create = node
            .service_builder(&service_name)
            .publish_subscribe::<Flatbuffer<u64>>()
            .flatbuffer_schema_path(schema_file.path().unwrap())
            .create();

        let sut = node
            .service_builder(&service_name)
            .publish_subscribe::<Flatbuffer<u64>>()
            .flatbuffer_schema_path(alt_schema_file.path().unwrap())
            .open();

        assert_that!(sut.err(), eq Some(PublishSubscribeOpenError::IncompatibleTypes));
    }

    #[conformance_test]
    pub fn open_succeeds_when_schema_content_is_identical<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let service_name = generate_service_name();
        let schema_file = create_schema_file(SCHEMA);
        let alt_schema_file = create_schema_file(SCHEMA);

        let _sut_create = node
            .service_builder(&service_name)
            .publish_subscribe::<Flatbuffer<u64>>()
            .flatbuffer_schema_path(schema_file.path().unwrap())
            .create();

        let sut = node
            .service_builder(&service_name)
            .publish_subscribe::<Flatbuffer<u64>>()
            .flatbuffer_schema_path(alt_schema_file.path().unwrap())
            .open();

        assert_that!(sut, is_ok);
    }

    #[conformance_test]
    pub fn service_schema_is_identical_to_origin<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let service_name = generate_service_name();
        let schema_file = create_schema_file(SCHEMA);

        let sut = node
            .service_builder(&service_name)
            .publish_subscribe::<Flatbuffer<u64>>()
            .flatbuffer_schema_path(schema_file.path().unwrap())
            .create()
            .unwrap();

        let type_definition = sut.type_definition().unwrap();

        assert_that!(type_definition.len(), eq SCHEMA.len() as u64);
        let mut buffer = vec![0u8; type_definition.len() as usize];
        type_definition.read(&mut buffer).unwrap();

        assert_that!(SCHEMA.as_bytes(), eq buffer.as_slice());
    }

    fn produce_example_data<'a, Sut: Service + 'static>(
        builder: &mut FlatBufferBuilder<'static, FlatbufferMemory<Sut>>,
        title: &str,
        data_1: i32,
        data_2: u64,
        number_of_entries: usize,
    ) -> WIPOffset<UnboundedData<'a>> {
        let title = builder.create_string(title);
        let mut entries = vec![];

        for _ in 0..number_of_entries {
            entries.push(Entry::create(builder, &EntryArgs { data_1, data_2 }));
        }
        let entries = builder.create_vector(&entries);
        UnboundedData::create(
            builder,
            &UnboundedDataArgs {
                title: Some(title),
                entries: Some(entries),
            },
        )
    }

    #[conformance_test]
    pub fn publish_subscribe_works<Sut: Service + 'static>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let service_name = generate_service_name();
        let schema_file = create_schema_file(SCHEMA);

        let sut = node
            .service_builder(&service_name)
            .publish_subscribe::<Flatbuffer<UnboundedData>>()
            .flatbuffer_schema_path(schema_file.path().unwrap())
            .create()
            .unwrap();

        let publisher = sut
            .publisher_builder()
            .initial_reserved_memory(4096)
            .create()
            .unwrap();
        let subscriber = sut.subscriber_builder().create().unwrap();

        let mut sample = publisher.loan_flatbuffer().unwrap();
        let builder = sample.flatbuffer_builder();
        let unbounded_data =
            produce_example_data(builder, "schorschi marked nalas territory", 123, 456, 1);
        sample.assume_init(unbounded_data).send().unwrap();

        let sample = subscriber.receive().unwrap().unwrap();
        let unbounded_data = sample.payload_root().unwrap();

        assert_that!(unbounded_data.title(), eq Some("schorschi marked nalas territory"));
        assert_that!(unbounded_data.entries().unwrap().len(), eq 1);
        assert_that!(unbounded_data.entries().unwrap().get(0).data_1(), eq 123);
        assert_that!(unbounded_data.entries().unwrap().get(0).data_2(), eq 456);
    }

    fn publisher_allocates_more_memory_when_initial_reserve_is_out<Sut: Service + 'static>(
        allocation_strategy: AllocationStrategy,
    ) {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let service_name = generate_service_name();
        let schema_file = create_schema_file(SCHEMA);

        let sut = node
            .service_builder(&service_name)
            .publish_subscribe::<Flatbuffer<UnboundedData>>()
            .flatbuffer_schema_path(schema_file.path().unwrap())
            .create()
            .unwrap();

        let publisher = sut
            .publisher_builder()
            .initial_reserved_memory(1)
            .allocation_strategy(allocation_strategy)
            .create()
            .unwrap();
        let subscriber = sut.subscriber_builder().create().unwrap();

        let mut sample = publisher.loan_flatbuffer().unwrap();
        let builder = sample.flatbuffer_builder();
        let unbounded_data =
            produce_example_data(builder, "go away, nothing to sniff here", 78, 9, 50);
        sample.assume_init(unbounded_data).send().unwrap();

        let sample = subscriber.receive().unwrap().unwrap();
        let unbounded_data = sample.payload_root().unwrap();

        assert_that!(unbounded_data.title(), eq Some("go away, nothing to sniff here"));
        assert_that!(unbounded_data.entries().unwrap().len(), eq 50);
        for n in 0..50 {
            assert_that!(unbounded_data.entries().unwrap().get(n).data_1(), eq 78);
            assert_that!(unbounded_data.entries().unwrap().get(n).data_2(), eq 9);
        }
    }

    #[conformance_test]
    pub fn publisher_allocates_more_memory_when_initial_reserve_is_out_with_allocation_strategy_power_of_two<
        Sut: Service + 'static,
    >() {
        publisher_allocates_more_memory_when_initial_reserve_is_out::<Sut>(
            AllocationStrategy::PowerOfTwo,
        );
    }

    #[conformance_test]
    pub fn publisher_allocates_more_memory_when_initial_reserve_is_out_with_allocation_strategy_best_fit<
        Sut: Service + 'static,
    >() {
        publisher_allocates_more_memory_when_initial_reserve_is_out::<Sut>(
            AllocationStrategy::BestFit,
        );
    }

    #[should_panic]
    #[conformance_test]
    pub fn publisher_does_not_allocate_when_allocation_strategy_is_static<
        Sut: Service + 'static,
    >() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let service_name = generate_service_name();
        let schema_file = create_schema_file(SCHEMA);

        let sut = node
            .service_builder(&service_name)
            .publish_subscribe::<Flatbuffer<UnboundedData>>()
            .flatbuffer_schema_path(schema_file.path().unwrap())
            .create()
            .unwrap();

        let publisher = sut
            .publisher_builder()
            .initial_reserved_memory(1)
            .allocation_strategy(AllocationStrategy::Static)
            .create()
            .unwrap();

        let mut sample = publisher.loan_flatbuffer().unwrap();
        let builder = sample.flatbuffer_builder();

        // panics here. flatbuffer handles out-of-memory from the allocator always with a panic and
        // does not support any clean error handling
        let _title = builder.create_string("oh no more memory");
    }

    #[conformance_test]
    pub fn data_can_be_reconstructed_from_payload_bytes<Sut: Service + 'static>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let service_name = generate_service_name();
        let schema_file = create_schema_file(SCHEMA);

        let sut = node
            .service_builder(&service_name)
            .publish_subscribe::<Flatbuffer<UnboundedData>>()
            .flatbuffer_schema_path(schema_file.path().unwrap())
            .create()
            .unwrap();

        let publisher = sut
            .publisher_builder()
            .initial_reserved_memory(4096)
            .create()
            .unwrap();
        let subscriber = sut.subscriber_builder().create().unwrap();

        let mut sample = publisher.loan_flatbuffer().unwrap();
        let builder = sample.flatbuffer_builder();
        let unbounded_data =
            produce_example_data(builder, "there is a butterfly on nalas nose", 44, 55, 1);
        sample.assume_init(unbounded_data).send().unwrap();

        let sample = subscriber.receive().unwrap().unwrap();
        let unbounded_data = root_as_unbounded_data(sample.payload_bytes()).unwrap();

        assert_that!(unbounded_data.title(), eq Some("there is a butterfly on nalas nose"));
        assert_that!(unbounded_data.entries().unwrap().len(), eq 1);
        for n in 0..1 {
            assert_that!(unbounded_data.entries().unwrap().get(n).data_1(), eq 44);
            assert_that!(unbounded_data.entries().unwrap().get(n).data_2(), eq 55);
        }
    }
}
