// Copyright (c) 2026 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Apache Software License 2.0 which is available at
// https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
// which is available at https://opensource.org/licenses/MIT.
//
// SPDX-License-Identifier: Apache-2.0 OR MIT

extern crate alloc;

use iceoryx2_bb_testing_macros::conformance_tests;

#[allow(clippy::module_inception)]
#[conformance_tests]
pub mod service_request_response_flatbuffer {
    use alloc::vec;
    use flatbuffers::{FlatBufferBuilder, WIPOffset};
    use iceoryx2::service::builder::request_response::{
        RequestResponseCreateError, RequestResponseOpenError,
    };
    use iceoryx2::service::{Service, marker::Flatbuffer};
    use iceoryx2_bb_elementary::allocation_strategy::AllocationStrategy;
    use iceoryx2_bb_posix::config::TEST_DIRECTORY;
    use iceoryx2_bb_posix::testing::*;
    use iceoryx2_bb_testing::assert_that;
    use iceoryx2_bb_testing_macros::conformance_test;
    use iceoryx2_cal::static_storage::StaticStorageView;
    use iceoryx2_testing::*;

    //////////////////////////////
    // START: generated by flatc
    //////////////////////////////
    #[allow(unused_imports, dead_code)]
    pub mod example {

        extern crate alloc;

        pub enum DataPropsOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct DataProps<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for DataProps<'a> {
            type Inner = DataProps<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> DataProps<'a> {
            pub const VT_RECEIVED_ENTRIES_LEN: ::flatbuffers::VOffsetT = 4;

            #[inline]
            /// # Safety
            ///  code generated
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                DataProps { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args DataPropsArgs,
            ) -> ::flatbuffers::WIPOffset<DataProps<'bldr>> {
                let mut builder = DataPropsBuilder::new(_fbb);
                builder.add_received_entries_len(args.received_entries_len);
                builder.finish()
            }

            #[inline]
            pub fn received_entries_len(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u64>(DataProps::VT_RECEIVED_ENTRIES_LEN, Some(0))
                        .unwrap()
                }
            }
        }

        impl ::flatbuffers::Verifiable for DataProps<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<u64>(
                        "received_entries_len",
                        Self::VT_RECEIVED_ENTRIES_LEN,
                        false,
                    )?
                    .finish();
                Ok(())
            }
        }
        pub struct DataPropsArgs {
            pub received_entries_len: u64,
        }
        impl Default for DataPropsArgs {
            #[inline]
            fn default() -> Self {
                DataPropsArgs {
                    received_entries_len: 0,
                }
            }
        }

        pub struct DataPropsBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DataPropsBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_received_entries_len(&mut self, received_entries_len: u64) {
                self.fbb_.push_slot::<u64>(
                    DataProps::VT_RECEIVED_ENTRIES_LEN,
                    received_entries_len,
                    0,
                );
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> DataPropsBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                DataPropsBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<DataProps<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for DataProps<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("DataProps");
                ds.field("received_entries_len", &self.received_entries_len());
                ds.finish()
            }
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a `DataProps`
        /// and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_data_props_unchecked`.
        pub fn root_as_data_props(
            buf: &[u8],
        ) -> Result<DataProps<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root::<DataProps>(buf)
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a size prefixed
        /// `DataProps` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `size_prefixed_root_as_data_props_unchecked`.
        pub fn size_prefixed_root_as_data_props(
            buf: &[u8],
        ) -> Result<DataProps<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root::<DataProps>(buf)
        }
        #[inline]
        /// Verifies, with the given options, that a buffer of bytes
        /// contains a `DataProps` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_data_props_unchecked`.
        pub fn root_as_data_props_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<DataProps<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root_with_opts::<DataProps<'b>>(opts, buf)
        }
        #[inline]
        /// Verifies, with the given verifier options, that a buffer of
        /// bytes contains a size prefixed `DataProps` and returns
        /// it. Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_data_props_unchecked`.
        pub fn size_prefixed_root_as_data_props_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<DataProps<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root_with_opts::<DataProps<'b>>(opts, buf)
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a DataProps and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid `DataProps`.
        pub unsafe fn root_as_data_props_unchecked(buf: &[u8]) -> DataProps<'_> {
            unsafe { ::flatbuffers::root_unchecked::<DataProps>(buf) }
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a size prefixed DataProps and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid size prefixed `DataProps`.
        pub unsafe fn size_prefixed_root_as_data_props_unchecked(buf: &[u8]) -> DataProps<'_> {
            unsafe { ::flatbuffers::size_prefixed_root_unchecked::<DataProps>(buf) }
        }
        #[inline]
        pub fn finish_data_props_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<DataProps<'a>>,
        ) {
            fbb.finish(root, None);
        }

        #[inline]
        pub fn finish_size_prefixed_data_props_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<DataProps<'a>>,
        ) {
            fbb.finish_size_prefixed(root, None);
        }

        pub enum EntryOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct Entry<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for Entry<'a> {
            type Inner = Entry<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> Entry<'a> {
            pub const VT_DATA_1: ::flatbuffers::VOffsetT = 4;
            pub const VT_DATA_2: ::flatbuffers::VOffsetT = 6;

            #[inline]
            unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                Entry { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args EntryArgs,
            ) -> ::flatbuffers::WIPOffset<Entry<'bldr>> {
                let mut builder = EntryBuilder::new(_fbb);
                builder.add_data_2(args.data_2);
                builder.add_data_1(args.data_1);
                builder.finish()
            }

            #[inline]
            pub fn data_1(&self) -> i32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<i32>(Entry::VT_DATA_1, Some(0)).unwrap() }
            }
            #[inline]
            pub fn data_2(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u64>(Entry::VT_DATA_2, Some(0)).unwrap() }
            }
        }

        impl ::flatbuffers::Verifiable for Entry<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<i32>("data_1", Self::VT_DATA_1, false)?
                    .visit_field::<u64>("data_2", Self::VT_DATA_2, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct EntryArgs {
            pub data_1: i32,
            pub data_2: u64,
        }
        impl Default for EntryArgs {
            #[inline]
            fn default() -> Self {
                EntryArgs {
                    data_1: 0,
                    data_2: 0,
                }
            }
        }

        pub struct EntryBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> EntryBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_data_1(&mut self, data_1: i32) {
                self.fbb_.push_slot::<i32>(Entry::VT_DATA_1, data_1, 0);
            }
            #[inline]
            pub fn add_data_2(&mut self, data_2: u64) {
                self.fbb_.push_slot::<u64>(Entry::VT_DATA_2, data_2, 0);
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> EntryBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                EntryBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<Entry<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for Entry<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("Entry");
                ds.field("data_1", &self.data_1());
                ds.field("data_2", &self.data_2());
                ds.finish()
            }
        }
        pub enum UnboundedDataOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct UnboundedData<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for UnboundedData<'a> {
            type Inner = UnboundedData<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> UnboundedData<'a> {
            pub const VT_TITLE: ::flatbuffers::VOffsetT = 4;
            pub const VT_ENTRIES: ::flatbuffers::VOffsetT = 6;

            #[inline]
            unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                UnboundedData { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args UnboundedDataArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<UnboundedData<'bldr>> {
                let mut builder = UnboundedDataBuilder::new(_fbb);
                if let Some(x) = args.entries {
                    builder.add_entries(x);
                }
                if let Some(x) = args.title {
                    builder.add_title(x);
                }
                builder.finish()
            }

            #[inline]
            pub fn title(&self) -> Option<&'a str> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<::flatbuffers::ForwardsUOffset<&str>>(UnboundedData::VT_TITLE, None)
                }
            }
            #[inline]
            pub fn entries(
                &self,
            ) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Entry<'a>>>>
            {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<::flatbuffers::ForwardsUOffset<
                        ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Entry>>,
                    >>(UnboundedData::VT_ENTRIES, None)
                }
            }
        }

        impl ::flatbuffers::Verifiable for UnboundedData<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                        "title",
                        Self::VT_TITLE,
                        false,
                    )?
                    .visit_field::<::flatbuffers::ForwardsUOffset<
                        ::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Entry>>,
                    >>("entries", Self::VT_ENTRIES, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct UnboundedDataArgs<'a> {
            pub title: Option<::flatbuffers::WIPOffset<&'a str>>,
            pub entries: Option<
                ::flatbuffers::WIPOffset<
                    ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Entry<'a>>>,
                >,
            >,
        }
        impl<'a> Default for UnboundedDataArgs<'a> {
            #[inline]
            fn default() -> Self {
                UnboundedDataArgs {
                    title: None,
                    entries: None,
                }
            }
        }

        pub struct UnboundedDataBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> UnboundedDataBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_title(&mut self, title: ::flatbuffers::WIPOffset<&'b str>) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    UnboundedData::VT_TITLE,
                    title,
                );
            }
            #[inline]
            pub fn add_entries(
                &mut self,
                entries: ::flatbuffers::WIPOffset<
                    ::flatbuffers::Vector<'b, ::flatbuffers::ForwardsUOffset<Entry<'b>>>,
                >,
            ) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    UnboundedData::VT_ENTRIES,
                    entries,
                );
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> UnboundedDataBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                UnboundedDataBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<UnboundedData<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for UnboundedData<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("UnboundedData");
                ds.field("title", &self.title());
                ds.field("entries", &self.entries());
                ds.finish()
            }
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a `UnboundedData`
        /// and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_unbounded_data_unchecked`.
        pub fn root_as_unbounded_data(
            buf: &[u8],
        ) -> Result<UnboundedData<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root::<UnboundedData>(buf)
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a size prefixed
        /// `UnboundedData` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `size_prefixed_root_as_unbounded_data_unchecked`.
        pub fn size_prefixed_root_as_unbounded_data(
            buf: &[u8],
        ) -> Result<UnboundedData<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root::<UnboundedData>(buf)
        }
        #[inline]
        /// Verifies, with the given options, that a buffer of bytes
        /// contains a `UnboundedData` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_unbounded_data_unchecked`.
        pub fn root_as_unbounded_data_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<UnboundedData<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root_with_opts::<UnboundedData<'b>>(opts, buf)
        }
        #[inline]
        /// Verifies, with the given verifier options, that a buffer of
        /// bytes contains a size prefixed `UnboundedData` and returns
        /// it. Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_unbounded_data_unchecked`.
        pub fn size_prefixed_root_as_unbounded_data_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<UnboundedData<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root_with_opts::<UnboundedData<'b>>(opts, buf)
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a UnboundedData and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid `UnboundedData`.
        pub unsafe fn root_as_unbounded_data_unchecked(buf: &[u8]) -> UnboundedData<'_> {
            unsafe { ::flatbuffers::root_unchecked::<UnboundedData>(buf) }
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a size prefixed UnboundedData and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid size prefixed `UnboundedData`.
        pub unsafe fn size_prefixed_root_as_unbounded_data_unchecked(
            buf: &[u8],
        ) -> UnboundedData<'_> {
            unsafe { ::flatbuffers::size_prefixed_root_unchecked::<UnboundedData>(buf) }
        }
        #[inline]
        pub fn finish_unbounded_data_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<UnboundedData<'a>>,
        ) {
            fbb.finish(root, None);
        }

        #[inline]
        pub fn finish_size_prefixed_unbounded_data_buffer<
            'a,
            'b,
            A: ::flatbuffers::Allocator + 'a,
        >(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<UnboundedData<'a>>,
        ) {
            fbb.finish_size_prefixed(root, None);
        }
    }
    //////////////////////////////
    // END: generated by flatc
    //////////////////////////////

    const DATA_PROPS_SCHEMA: &str = "
        namespace Example;

        table DataProps {
            received_entries_len: uint64;
        }

        root_type DataProps;
    ";

    const UNBOUND_DATA_SCHEMA: &str = "
        namespace Example;

        table Entry {
            data_1: int32;
            data_2: uint64;
        }

        table UnboundedData {
            title: string;
            entries: [Entry];
        }

        root_type UnboundedData;
    ";

    #[conformance_test]
    pub fn create_fails_when_no_schema_file_is_available_for_request<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let service_name = generate_service_name();
        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, u64>()
            .create();

        assert_that!(sut.err(), eq Some(RequestResponseCreateError::UnableToAcquireTypeDefinition));
    }

    #[conformance_test]
    pub fn create_fails_when_no_schema_file_is_available_for_response<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let service_name = generate_service_name();
        let sut = node
            .service_builder(&service_name)
            .request_response::<u64, Flatbuffer<u64>>()
            .create();

        assert_that!(sut.err(), eq Some(RequestResponseCreateError::UnableToAcquireTypeDefinition));
    }

    #[conformance_test]
    pub fn create_succeeds_with_request_schema_file<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let schema_file = create_file_with_content(UNBOUND_DATA_SCHEMA);

        let service_name = generate_service_name();
        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, u64>()
            .request_flatbuffer_schema_path(schema_file.path().unwrap())
            .create();

        assert_that!(sut, is_ok);
    }

    #[conformance_test]
    pub fn create_succeeds_with_response_schema_file<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let schema_file = create_file_with_content(UNBOUND_DATA_SCHEMA);

        let service_name = generate_service_name();
        let sut = node
            .service_builder(&service_name)
            .request_response::<u64, Flatbuffer<u64>>()
            .response_flatbuffer_schema_path(schema_file.path().unwrap())
            .create();

        assert_that!(sut, is_ok);
    }

    #[conformance_test]
    pub fn create_succeeds_with_request_and_response_schema_file<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let schema_file = create_file_with_content(UNBOUND_DATA_SCHEMA);

        let service_name = generate_service_name();
        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, Flatbuffer<u64>>()
            .request_flatbuffer_schema_path(schema_file.path().unwrap())
            .response_flatbuffer_schema_path(schema_file.path().unwrap())
            .create();

        assert_that!(sut, is_ok);
    }

    #[conformance_test]
    pub fn open_fails_when_no_request_schema_file_is_available<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let schema_file = create_file_with_content(UNBOUND_DATA_SCHEMA);

        let service_name = generate_service_name();
        let _sut_create = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, u64>()
            .request_flatbuffer_schema_path(schema_file.path().unwrap())
            .create();

        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, u64>()
            .open();

        assert_that!(sut.err(), eq Some(RequestResponseOpenError::UnableToAcquireTypeDefinition));
    }

    #[conformance_test]
    pub fn open_fails_when_no_response_schema_file_is_available<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let schema_file = create_file_with_content(UNBOUND_DATA_SCHEMA);

        let service_name = generate_service_name();
        let _sut_create = node
            .service_builder(&service_name)
            .request_response::<u64, Flatbuffer<u64>>()
            .response_flatbuffer_schema_path(schema_file.path().unwrap())
            .create();

        let sut = node
            .service_builder(&service_name)
            .request_response::<u64, Flatbuffer<u64>>()
            .open();

        assert_that!(sut.err(), eq Some(RequestResponseOpenError::UnableToAcquireTypeDefinition));
    }

    #[conformance_test]
    pub fn open_fails_when_request_schema_file_is_not_the_same<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let schema_file = create_file_with_content(UNBOUND_DATA_SCHEMA);
        let alt_schema_file = create_file_with_content(DATA_PROPS_SCHEMA);

        let service_name = generate_service_name();
        let _sut_create = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, Flatbuffer<u64>>()
            .request_flatbuffer_schema_path(schema_file.path().unwrap())
            .response_flatbuffer_schema_path(schema_file.path().unwrap())
            .create();

        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, Flatbuffer<u64>>()
            .request_flatbuffer_schema_path(alt_schema_file.path().unwrap())
            .response_flatbuffer_schema_path(schema_file.path().unwrap())
            .open();

        assert_that!(sut.err(), eq Some(RequestResponseOpenError::IncompatibleRequestOrResponseType));
    }

    #[conformance_test]
    pub fn open_fails_when_response_schema_file_is_not_the_same<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let schema_file = create_file_with_content(UNBOUND_DATA_SCHEMA);
        let alt_schema_file = create_file_with_content(DATA_PROPS_SCHEMA);

        let service_name = generate_service_name();
        let _sut_create = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, Flatbuffer<u64>>()
            .request_flatbuffer_schema_path(schema_file.path().unwrap())
            .response_flatbuffer_schema_path(schema_file.path().unwrap())
            .create();

        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, Flatbuffer<u64>>()
            .request_flatbuffer_schema_path(schema_file.path().unwrap())
            .response_flatbuffer_schema_path(alt_schema_file.path().unwrap())
            .open();

        assert_that!(sut.err(), eq Some(RequestResponseOpenError::IncompatibleRequestOrResponseType));
    }

    #[conformance_test]
    pub fn open_succeeds_when_schema_content_is_identical<Sut: Service>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let schema_file = create_file_with_content(UNBOUND_DATA_SCHEMA);
        let alt_schema_file = create_file_with_content(DATA_PROPS_SCHEMA);

        let service_name = generate_service_name();
        let _sut_create = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, Flatbuffer<u64>>()
            .request_flatbuffer_schema_path(schema_file.path().unwrap())
            .response_flatbuffer_schema_path(alt_schema_file.path().unwrap())
            .create();

        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, Flatbuffer<u64>>()
            .request_flatbuffer_schema_path(schema_file.path().unwrap())
            .response_flatbuffer_schema_path(alt_schema_file.path().unwrap())
            .open();

        assert_that!(sut, is_ok);
    }

    #[conformance_test]
    pub fn schema_path_lookup_works_when_creating_a_service<Sut: Service>() {
        let mut test = Test::<Sut>::new();
        test.config_mut().global.service.flatbuffer_schema_path = Some(TEST_DIRECTORY);
        let node = test.create_node();
        let _schema_file = create_file_with_content_at(UNBOUND_DATA_SCHEMA, "unbounded_data.fbs");
        let _alt_schema_file = create_file_with_content_at(DATA_PROPS_SCHEMA, "data_props.fbs");

        let service_name = generate_service_name();
        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<example::UnboundedData>, Flatbuffer<example::DataProps>>(
            )
            .create();

        assert_that!(sut, is_ok);
    }

    #[conformance_test]
    pub fn schema_path_lookup_works_when_opening_a_service<Sut: Service>() {
        let mut test = Test::<Sut>::new();
        test.config_mut().global.service.flatbuffer_schema_path = Some(TEST_DIRECTORY);
        let node = test.create_node();
        let _schema_file = create_file_with_content_at(UNBOUND_DATA_SCHEMA, "unbounded_data.fbs");
        let _alt_schema_file = create_file_with_content_at(DATA_PROPS_SCHEMA, "data_props.fbs");

        let service_name = generate_service_name();
        let _sut_create = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<example::UnboundedData>, Flatbuffer<example::DataProps>>(
            )
            .create();

        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<example::UnboundedData>, Flatbuffer<example::DataProps>>(
            )
            .open();

        assert_that!(sut, is_ok);
    }

    #[conformance_test]
    pub fn request_schema_is_identical_to_origin<Sut: Service>() {
        let mut test = Test::<Sut>::new();
        test.config_mut().global.service.flatbuffer_schema_path = Some(TEST_DIRECTORY);
        let node = test.create_node();
        let schema_file = create_file_with_content_at(UNBOUND_DATA_SCHEMA, "unbounded_data.fbs");
        let alt_schema_file = create_file_with_content_at(DATA_PROPS_SCHEMA, "data_props.fbs");

        let service_name = generate_service_name();
        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, Flatbuffer<u64>>()
            .request_flatbuffer_schema_path(schema_file.path().unwrap())
            .response_flatbuffer_schema_path(alt_schema_file.path().unwrap())
            .create()
            .unwrap();

        let type_definition = sut.request_type_definition().unwrap();

        assert_that!(type_definition.len(), eq UNBOUND_DATA_SCHEMA.len() as u64);
        let mut buffer = vec![0u8; UNBOUND_DATA_SCHEMA.len()];
        type_definition.read(&mut buffer).unwrap();

        assert_that!(UNBOUND_DATA_SCHEMA.as_bytes(), eq buffer.as_slice());
    }

    #[conformance_test]
    pub fn response_schema_is_identical_to_origin<Sut: Service>() {
        let mut test = Test::<Sut>::new();
        test.config_mut().global.service.flatbuffer_schema_path = Some(TEST_DIRECTORY);
        let node = test.create_node();
        let schema_file = create_file_with_content_at(UNBOUND_DATA_SCHEMA, "unbounded_data.fbs");
        let alt_schema_file = create_file_with_content_at(DATA_PROPS_SCHEMA, "data_props.fbs");

        let service_name = generate_service_name();
        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<u64>, Flatbuffer<u64>>()
            .request_flatbuffer_schema_path(schema_file.path().unwrap())
            .response_flatbuffer_schema_path(alt_schema_file.path().unwrap())
            .create()
            .unwrap();

        let type_definition = sut.response_type_definition().unwrap();

        assert_that!(type_definition.len(), eq DATA_PROPS_SCHEMA.len() as u64);
        let mut buffer = vec![0u8; DATA_PROPS_SCHEMA.len()];
        type_definition.read(&mut buffer).unwrap();

        assert_that!(DATA_PROPS_SCHEMA.as_bytes(), eq buffer.as_slice());
    }

    fn produce_request_data<'a, Sut: Service + 'static>(
        builder: &mut FlatBufferBuilder<
            'static,
            iceoryx2::request_mut_uninit::FlatbufferMemory<Sut>,
        >,
        title: &str,
        data_1: i32,
        data_2: u64,
        number_of_entries: usize,
    ) -> WIPOffset<example::UnboundedData<'a>> {
        let title = builder.create_string(title);
        let mut entries = vec![];

        for _ in 0..number_of_entries {
            entries.push(example::Entry::create(
                builder,
                &example::EntryArgs { data_1, data_2 },
            ));
        }
        let entries = builder.create_vector(&entries);
        example::UnboundedData::create(
            builder,
            &example::UnboundedDataArgs {
                title: Some(title),
                entries: Some(entries),
            },
        )
    }

    fn produce_response_data<'a, Sut: Service + 'static>(
        builder: &mut FlatBufferBuilder<
            'static,
            iceoryx2::response_mut_uninit::FlatbufferMemory<Sut>,
        >,
        title: &str,
        data_1: i32,
        data_2: u64,
        number_of_entries: usize,
    ) -> WIPOffset<example::UnboundedData<'a>> {
        let title = builder.create_string(title);
        let mut entries = vec![];

        for _ in 0..number_of_entries {
            entries.push(example::Entry::create(
                builder,
                &example::EntryArgs { data_1, data_2 },
            ));
        }
        let entries = builder.create_vector(&entries);
        example::UnboundedData::create(
            builder,
            &example::UnboundedDataArgs {
                title: Some(title),
                entries: Some(entries),
            },
        )
    }

    ////////////////////////////////////////////
    // REQUEST TESTS
    ////////////////////////////////////////////

    #[conformance_test]
    pub fn sending_request_works<Sut: Service + 'static>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let service_name = generate_service_name();
        let request_schema_file = create_file_with_content(UNBOUND_DATA_SCHEMA);
        let response_schema_file = create_file_with_content(DATA_PROPS_SCHEMA);

        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<example::UnboundedData>, Flatbuffer<example::DataProps>>(
            )
            .request_flatbuffer_schema_path(request_schema_file.path().unwrap())
            .response_flatbuffer_schema_path(response_schema_file.path().unwrap())
            .create()
            .unwrap();

        let client = sut
            .client_builder()
            .initial_reserved_memory(4096)
            .create()
            .unwrap();
        let server = sut.server_builder().create().unwrap();

        let mut request = client.loan_flatbuffer().unwrap();
        let builder = request.flatbuffer_builder();
        let unbounded_data = produce_request_data(
            builder,
            "The Hoff is looking for padding bytes.",
            551,
            661,
            11,
        );
        let _pending_response = request.assume_init(unbounded_data).send().unwrap();

        let active_request = server.receive().unwrap().unwrap();
        let unbounded_data = active_request.payload_root().unwrap();

        assert_that!(unbounded_data.title(), eq Some("The Hoff is looking for padding bytes."));
        assert_that!(unbounded_data.entries().unwrap().len(), eq 11);

        for i in 0..11 {
            assert_that!(unbounded_data.entries().unwrap().get(i).data_1(), eq 551);
            assert_that!(unbounded_data.entries().unwrap().get(i).data_2(), eq 661);
        }
    }

    fn client_allocates_more_memory_when_initial_reserve_is_out<Sut: Service + 'static>(
        allocation_strategy: AllocationStrategy,
    ) {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let service_name = generate_service_name();
        let request_schema_file = create_file_with_content(UNBOUND_DATA_SCHEMA);
        let response_schema_file = create_file_with_content(DATA_PROPS_SCHEMA);

        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<example::UnboundedData>, Flatbuffer<example::DataProps>>(
            )
            .request_flatbuffer_schema_path(request_schema_file.path().unwrap())
            .response_flatbuffer_schema_path(response_schema_file.path().unwrap())
            .create()
            .unwrap();

        let client = sut
            .client_builder()
            .initial_reserved_memory(1)
            .allocation_strategy(allocation_strategy)
            .create()
            .unwrap();
        let server = sut.server_builder().create().unwrap();

        let mut request = client.loan_flatbuffer().unwrap();
        let builder = request.flatbuffer_builder();
        let unbounded_data = produce_request_data(
            builder,
            "Not another request, gimme cheese!",
            4712,
            4710,
            50,
        );
        let _pending_response = request.assume_init(unbounded_data).send().unwrap();

        let active_request = server.receive().unwrap().unwrap();
        let unbounded_data = active_request.payload_root().unwrap();

        assert_that!(unbounded_data.title(), eq Some("Not another request, gimme cheese!"));
        assert_that!(unbounded_data.entries().unwrap().len(), eq 50);
        for n in 0..50 {
            assert_that!(unbounded_data.entries().unwrap().get(n).data_1(), eq 4712);
            assert_that!(unbounded_data.entries().unwrap().get(n).data_2(), eq 4710);
        }
    }

    #[conformance_test]
    pub fn client_allocates_more_memory_when_initial_reserve_is_out_with_allocation_strategy_power_of_two<
        Sut: Service + 'static,
    >() {
        client_allocates_more_memory_when_initial_reserve_is_out::<Sut>(
            AllocationStrategy::PowerOfTwo,
        );
    }

    #[conformance_test]
    pub fn client_allocates_more_memory_when_initial_reserve_is_out_with_allocation_strategy_best_fit<
        Sut: Service + 'static,
    >() {
        client_allocates_more_memory_when_initial_reserve_is_out::<Sut>(
            AllocationStrategy::BestFit,
        );
    }

    #[should_panic]
    #[conformance_test]
    pub fn client_does_not_allocate_when_allocation_strategy_is_static<Sut: Service + 'static>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let service_name = generate_service_name();
        let request_schema_file = create_file_with_content(UNBOUND_DATA_SCHEMA);
        let response_schema_file = create_file_with_content(DATA_PROPS_SCHEMA);

        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<example::UnboundedData>, Flatbuffer<example::DataProps>>(
            )
            .request_flatbuffer_schema_path(request_schema_file.path().unwrap())
            .response_flatbuffer_schema_path(response_schema_file.path().unwrap())
            .create()
            .unwrap();

        let client = sut
            .client_builder()
            .initial_reserved_memory(1)
            .allocation_strategy(AllocationStrategy::Static)
            .create()
            .unwrap();

        let mut request = client.loan_flatbuffer().unwrap();
        let builder = request.flatbuffer_builder();

        // panics here. flatbuffer handles out-of-memory from the allocator always with a panic and
        // does not support any clean error handling
        let _title = builder.create_string("oh no more memory");
    }

    #[conformance_test]
    pub fn request_data_can_be_reconstructed_from_payload_bytes<Sut: Service + 'static>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let service_name = generate_service_name();
        let request_schema_file = create_file_with_content(UNBOUND_DATA_SCHEMA);
        let response_schema_file = create_file_with_content(DATA_PROPS_SCHEMA);

        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<example::UnboundedData>, Flatbuffer<example::DataProps>>(
            )
            .request_flatbuffer_schema_path(request_schema_file.path().unwrap())
            .response_flatbuffer_schema_path(response_schema_file.path().unwrap())
            .create()
            .unwrap();

        let client = sut
            .client_builder()
            .initial_reserved_memory(4096)
            .create()
            .unwrap();
        let server = sut.server_builder().create().unwrap();

        let mut request = client.loan_flatbuffer().unwrap();
        let builder = request.flatbuffer_builder();
        let unbounded_data = produce_request_data(builder, "Whoop dii doo", 1144, 1155, 11);
        let _pending_response = request.assume_init(unbounded_data).send().unwrap();

        let active_request = server.receive().unwrap().unwrap();
        let unbounded_data =
            example::root_as_unbounded_data(active_request.payload_bytes()).unwrap();

        assert_that!(unbounded_data.title(), eq Some("Whoop dii doo"));
        assert_that!(unbounded_data.entries().unwrap().len(), eq 11);
        for n in 0..11 {
            assert_that!(unbounded_data.entries().unwrap().get(n).data_1(), eq 1144);
            assert_that!(unbounded_data.entries().unwrap().get(n).data_2(), eq 1155);
        }
    }

    #[conformance_test]
    pub fn client_can_read_its_own_serialized_data<Sut: Service + 'static>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let service_name = generate_service_name();
        let request_schema_file = create_file_with_content(UNBOUND_DATA_SCHEMA);
        let response_schema_file = create_file_with_content(DATA_PROPS_SCHEMA);

        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<example::UnboundedData>, Flatbuffer<example::DataProps>>(
            )
            .request_flatbuffer_schema_path(request_schema_file.path().unwrap())
            .response_flatbuffer_schema_path(response_schema_file.path().unwrap())
            .create()
            .unwrap();

        let client = sut
            .client_builder()
            .initial_reserved_memory(4096)
            .create()
            .unwrap();

        let mut request = client.loan_flatbuffer().unwrap();
        let builder = request.flatbuffer_builder();
        let unbounded_data =
            produce_request_data(builder, "dogs do not have a belly button", 980128, 5551, 10);
        let request = request.assume_init(unbounded_data);

        let verify = |unbounded_data: example::UnboundedData<'_>| {
            assert_that!(unbounded_data.title(), eq Some("dogs do not have a belly button"));
            assert_that!(unbounded_data.entries().unwrap().len(), eq 10);
            for n in 0..10 {
                assert_that!(unbounded_data.entries().unwrap().get(n).data_1(), eq 980128);
                assert_that!(unbounded_data.entries().unwrap().get(n).data_2(), eq 5551);
            }
        };

        verify(request.payload_root().unwrap());

        let pending_response = request.send().unwrap();
        verify(pending_response.payload_root().unwrap());
    }

    #[conformance_test]
    pub fn request_with_user_header_works<Sut: Service + 'static>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let service_name = generate_service_name();
        let request_schema_file = create_file_with_content(UNBOUND_DATA_SCHEMA);
        let response_schema_file = create_file_with_content(DATA_PROPS_SCHEMA);

        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<example::UnboundedData>, Flatbuffer<example::DataProps>>(
            )
            .request_flatbuffer_schema_path(request_schema_file.path().unwrap())
            .response_flatbuffer_schema_path(response_schema_file.path().unwrap())
            .request_user_header::<u128>()
            .create()
            .unwrap();

        let client = sut
            .client_builder()
            .initial_reserved_memory(4096)
            .create()
            .unwrap();
        let server = sut.server_builder().create().unwrap();

        let mut request = client.loan_flatbuffer().unwrap();
        let builder = request.flatbuffer_builder();
        let unbounded_data =
            produce_request_data(builder, "banana joe is the new sonnenscheiner", 892, 895, 1);
        let mut request = request.assume_init(unbounded_data);
        *request.user_header_mut() = 891;
        let _pending_response = request.send().unwrap();

        let active_request = server.receive().unwrap().unwrap();
        let unbounded_data = active_request.payload_root().unwrap();

        assert_that!(*active_request.user_header(), eq 891);
        assert_that!(unbounded_data.title(), eq Some("banana joe is the new sonnenscheiner"));
        assert_that!(unbounded_data.entries().unwrap().len(), eq 1);
        assert_that!(unbounded_data.entries().unwrap().get(0).data_1(), eq 892);
        assert_that!(unbounded_data.entries().unwrap().get(0).data_2(), eq 895);
    }

    fn request_user_header_and_dynamic_reallocation_works<Sut: Service + 'static>(
        allocation_strategy: AllocationStrategy,
    ) {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let service_name = generate_service_name();
        let request_schema_file = create_file_with_content(UNBOUND_DATA_SCHEMA);
        let response_schema_file = create_file_with_content(DATA_PROPS_SCHEMA);

        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<example::UnboundedData>, Flatbuffer<example::DataProps>>(
            )
            .request_flatbuffer_schema_path(request_schema_file.path().unwrap())
            .response_flatbuffer_schema_path(response_schema_file.path().unwrap())
            .request_user_header::<u128>()
            .create()
            .unwrap();

        let client = sut
            .client_builder()
            .initial_reserved_memory(1)
            .allocation_strategy(allocation_strategy)
            .create()
            .unwrap();
        let server = sut.server_builder().create().unwrap();

        let mut request = client.loan_flatbuffer().unwrap();
        let builder = request.flatbuffer_builder();
        let unbounded_data = produce_request_data(
            builder,
            "Nala you have dirt on your snoot. What did you hide?",
            91,
            82,
            50,
        );
        let mut request = request.assume_init(unbounded_data);
        *request.user_header_mut() = 737373;
        request.send().unwrap();

        let active_request = server.receive().unwrap().unwrap();
        let unbounded_data = active_request.payload_root().unwrap();

        assert_that!(*active_request.user_header(), eq 737373);
        assert_that!(unbounded_data.title(), eq Some("Nala you have dirt on your snoot. What did you hide?"));
        assert_that!(unbounded_data.entries().unwrap().len(), eq 50);
        for i in 0..50 {
            assert_that!(unbounded_data.entries().unwrap().get(i).data_1(), eq 91);
            assert_that!(unbounded_data.entries().unwrap().get(i).data_2(), eq 82);
        }
    }

    #[conformance_test]
    pub fn request_user_header_and_dynamic_reallocation_works_with_allocation_strategy_power_of_two<
        Sut: Service + 'static,
    >() {
        request_user_header_and_dynamic_reallocation_works::<Sut>(AllocationStrategy::PowerOfTwo);
    }

    #[conformance_test]
    pub fn request_user_header_and_dynamic_reallocation_works_with_allocation_strategy_best_fit<
        Sut: Service + 'static,
    >() {
        request_user_header_and_dynamic_reallocation_works::<Sut>(AllocationStrategy::BestFit);
    }

    #[conformance_test]
    pub fn request_serialized_bytes_are_identical_on_client_and_server_side<
        Sut: Service + 'static,
    >() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let service_name = generate_service_name();
        let request_schema_file = create_file_with_content(UNBOUND_DATA_SCHEMA);
        let response_schema_file = create_file_with_content(DATA_PROPS_SCHEMA);

        let sut = node
            .service_builder(&service_name)
            .request_response::<Flatbuffer<example::UnboundedData>, Flatbuffer<example::DataProps>>(
            )
            .request_flatbuffer_schema_path(request_schema_file.path().unwrap())
            .response_flatbuffer_schema_path(response_schema_file.path().unwrap())
            .create()
            .unwrap();

        let client = sut
            .client_builder()
            .initial_reserved_memory(1)
            .allocation_strategy(AllocationStrategy::PowerOfTwo)
            .create()
            .unwrap();
        let server = sut.server_builder().create().unwrap();

        let mut request = client.loan_flatbuffer().unwrap();
        let builder = request.flatbuffer_builder();
        let unbounded_data =
            produce_request_data(builder, "Where is the cheese?", 79102, 7641728, 50);
        let request = request.assume_init(unbounded_data);
        let bytes = request.payload_bytes().to_vec();
        let pending_response = request.send().unwrap();
        assert_that!(pending_response.payload_bytes(), eq & bytes);

        let active_request = server.receive().unwrap().unwrap();
        assert_that!(active_request.payload_bytes(), eq & bytes);
    }

    ////////////////////////////////////////////
    // RESPONSE TESTS
    ////////////////////////////////////////////

    #[conformance_test]
    pub fn sending_response_works<Sut: Service + 'static>() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let service_name = generate_service_name();
        let response_schema_file = create_file_with_content(DATA_PROPS_SCHEMA);

        let sut = node
            .service_builder(&service_name)
            .request_response::<u64, Flatbuffer<example::UnboundedData>>()
            .response_flatbuffer_schema_path(response_schema_file.path().unwrap())
            .create()
            .unwrap();

        let client = sut.client_builder().create().unwrap();
        let server = sut
            .server_builder()
            .initial_reserved_memory(4096)
            .create()
            .unwrap();

        let pending_response = client.send_copy(0).unwrap();

        let active_request = server.receive().unwrap().unwrap();
        let mut response = active_request.loan_flatbuffer().unwrap();
        let builder = response.flatbuffer_builder();
        let data = produce_response_data(
            builder,
            "Look, there the Hoff rides on Hypnotoad.",
            4567,
            98776,
            25,
        );
        response.assume_init(data).send().unwrap();

        let response = pending_response.receive().unwrap().unwrap();
        let data = response.payload_root().unwrap();

        assert_that!(data.title(), eq Some("Look, there the Hoff rides on Hypnotoad."));
        assert_that!(data.entries().unwrap().len(), eq 25);
        for i in 0..25 {
            assert_that!(data.entries().unwrap().get(i).data_1(), eq 4567);
            assert_that!(data.entries().unwrap().get(i).data_2(), eq 98776);
        }
    }

    fn server_allocates_more_memory_when_initial_reserve_is_out<Sut: Service + 'static>(
        allocation_strategy: AllocationStrategy,
    ) {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let service_name = generate_service_name();
        let response_schema_file = create_file_with_content(DATA_PROPS_SCHEMA);

        let sut = node
            .service_builder(&service_name)
            .request_response::<u64, Flatbuffer<example::UnboundedData>>()
            .response_flatbuffer_schema_path(response_schema_file.path().unwrap())
            .create()
            .unwrap();

        let client = sut.client_builder().create().unwrap();
        let server = sut
            .server_builder()
            .initial_reserved_memory(1)
            .allocation_strategy(allocation_strategy)
            .create()
            .unwrap();

        let pending_response = client.send_copy(0).unwrap();

        let active_request = server.receive().unwrap().unwrap();
        let mut response = active_request.loan_flatbuffer().unwrap();
        let builder = response.flatbuffer_builder();
        let data = produce_response_data(
            builder,
            "Sleepy Nala dreams of the Big Hunt.",
            9191,
            1919,
            50,
        );
        response.assume_init(data).send().unwrap();

        let response = pending_response.receive().unwrap().unwrap();
        let data = response.payload_root().unwrap();

        assert_that!(data.title(), eq Some("Sleepy Nala dreams of the Big Hunt."));
        assert_that!(data.entries().unwrap().len(), eq 50);
        for i in 0..50 {
            assert_that!(data.entries().unwrap().get(i).data_1(), eq 9191);
            assert_that!(data.entries().unwrap().get(i).data_2(), eq 1919);
        }
    }

    #[conformance_test]
    pub fn server_allocates_more_memory_when_initial_reserve_is_out_with_allocation_strategy_power_of_two<
        Sut: Service + 'static,
    >() {
        server_allocates_more_memory_when_initial_reserve_is_out::<Sut>(
            AllocationStrategy::PowerOfTwo,
        );
    }

    #[conformance_test]
    pub fn server_allocates_more_memory_when_initial_reserve_is_out_with_allocation_strategy_best_fit<
        Sut: Service + 'static,
    >() {
        server_allocates_more_memory_when_initial_reserve_is_out::<Sut>(
            AllocationStrategy::BestFit,
        );
    }

    #[should_panic]
    #[conformance_test]
    pub fn server_does_not_allocate_more_memory_when_allocation_strategy_is_static<
        Sut: Service + 'static,
    >() {
        let test = Test::<Sut>::new();
        let node = test.create_node();
        let service_name = generate_service_name();
        let response_schema_file = create_file_with_content(DATA_PROPS_SCHEMA);

        let sut = node
            .service_builder(&service_name)
            .request_response::<u64, Flatbuffer<example::UnboundedData>>()
            .response_flatbuffer_schema_path(response_schema_file.path().unwrap())
            .create()
            .unwrap();

        let client = sut.client_builder().create().unwrap();
        let server = sut
            .server_builder()
            .initial_reserved_memory(1)
            .allocation_strategy(AllocationStrategy::Static)
            .create()
            .unwrap();

        let _pending_response = client.send_copy(0).unwrap();

        let active_request = server.receive().unwrap().unwrap();
        let mut response = active_request.loan_flatbuffer().unwrap();
        let builder = response.flatbuffer_builder();
        // panics here. flatbuffer handles out-of-memory from the allocator always with a panic and
        // does not support any clean error handling
        let _title = builder.create_string("oh no more memory");
    }
}
