#!/usr/bin/expect

#### Common Setup

set REPO_ROOT [exec git rev-parse --show-toplevel]
cd ${REPO_ROOT}

source examples/cross-language-end-to-end-tests/common.exp

#### Test Setup

set timeout 10

spawn python examples/python/event_multiplexing/notifier.py hypnotoad 42

spawn python examples/python/event_multiplexing/notifier.py brainslug 13

spawn python examples/python/event_multiplexing/wait.py hypnotoad brainslug

#### Test Assertion

expect_output "Received trigger from \" hypnotoad \""
expect_output "TriggerId(42)"
expect_output "Received trigger from \" brainslug \""
expect_output "TriggerId(13)"

show_test_passed
