#!/usr/bin/expect
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

#### Common Setup

set REPO_ROOT [exec git rev-parse --show-toplevel]
cd ${REPO_ROOT}

source examples/cross-language-end-to-end-tests/common.exp

#### Test Setup and Assertion

set timeout 20

spawn cargo run --example health_monitoring_central_daemon
set id_daemon $spawn_id
expect_output "Central daemon up and running."

spawn cargo run --example health_monitoring_publisher_1
set id_publisher_1 $spawn_id

spawn cargo run --example health_monitoring_publisher_2
set id_publisher_2 $spawn_id

spawn cargo run --example health_monitoring_subscriber
set id_subscriber $spawn_id

expect_output_from $id_publisher_1 "service_1: Send sample*"
expect_output_from $id_publisher_2 "service_2: Send sample*"
expect_output_from $id_subscriber "service_1: Received sample*"

exec kill -SIGKILL [exp_pid -i $id_publisher_1]

expect_output_from $id_daemon "detected dead node"

exec kill -SIGKILL [exp_pid -i $id_daemon]
exec kill -SIGKILL [exp_pid -i $id_publisher_2]

expect_output_from $id_subscriber "detected dead node"

show_test_passed
