#!/usr/bin/expect
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

#### Common Setup

set REPO_ROOT [exec git rev-parse --show-toplevel]
cd ${REPO_ROOT}

source examples/cross-language-end-to-end-tests/common.exp

#### Test Setup

set timeout 10

spawn cargo run --example blackboard_event_based_creator
set id_creator $spawn_id
# wait until ready
expect_output "Blackboard created."

spawn cargo run --example blackboard_event_based_opener

#### Test Assertion

expect_output_from $id_creator "Trigger event with entry id*"
expect_output "read: 5 for entry id*"

show_test_passed
