#!/usr/bin/expect

#### Common Setup

set REPO_ROOT [exec git rev-parse --show-toplevel]
cd ${REPO_ROOT}

source examples/cross-language-end-to-end-tests/common.exp

#### Test Setup

set timeout 10

spawn python examples/python/publish_subscribe/publisher.py

spawn python examples/python/publish_subscribe/subscriber.py

#### Test Assertion

expect_output "received: TransmissionData { x: 3, y: 9, funky: 2436.36 }*"

show_test_passed
