#!/usr/bin/expect
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

#### Common Setup

set REPO_ROOT [exec git rev-parse --show-toplevel]
cd ${REPO_ROOT}

source examples/cross-language-end-to-end-tests/common.exp

#### Test Setup

set timeout 10

spawn target/ff/cc/build/examples/cxx/service_attributes/example_cxx_service_attributes_creator
# wait until ready
expect_output "my_funky_service_name"

spawn target/ff/cc/build/examples/cxx/service_attributes/example_cxx_service_attributes_opener
set id_opener $spawn_id

spawn target/ff/cc/build/examples/cxx/service_attributes/example_cxx_service_attributes_incompatible
set id_incompatible $spawn_id

#### Test Assertion

expect_output_from $id_opener "camera_resolution"
expect_output_from $id_incompatible "camera_resolution: 3840x2160 -> not available"
expect_output_from $id_incompatible "camera_type -> not available"

show_test_passed
