#!/usr/bin/expect
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

#### Common Setup

set REPO_ROOT [exec git rev-parse --show-toplevel]
cd ${REPO_ROOT}

source examples/cross-language-end-to-end-tests/common.exp

#### Test Setup and Assertion

set timeout 10

spawn target/ff/cc/build/examples/c/publish_subscribe/example_c_subscriber
expect_output "Subscriber ready to receive data!"

spawn target/ff/cc/build/examples/c/discovery/example_c_discovery
expect_output "Found Service: My/Funk/ServiceName*"

spawn target/ff/cc/build/examples/c/event/example_c_event_listener
expect_output "Listener ready to receive events!"

spawn target/ff/cc/build/examples/c/discovery/example_c_discovery
expect_output "Found Service: MyEventName*"

show_test_passed
