#!/usr/bin/expect
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

#### Common Setup

set REPO_ROOT [exec git rev-parse --show-toplevel]
cd ${REPO_ROOT}

source examples/cross-language-end-to-end-tests/common.exp

#### Test Setup

set timeout 10

spawn target/ff/cc/build/examples/cxx/event_multiplexing/example_cxx_event_multiplexing_notifier --service hypnotoad --event-id 42
set id_notifier_1 $spawn_id

spawn target/ff/cc/build/examples/cxx/event_multiplexing/example_cxx_event_multiplexing_notifier --service brainslug --event-id 13
set id_notifier_2 $spawn_id

spawn target/ff/cc/build/examples/cxx/event_multiplexing/example_cxx_event_multiplexing_wait --service1 hypnotoad --service2 brainslug

#### Test Assertion

expect_output_from $id_notifier_1 "Trigger event with id*"
expect_output_from $id_notifier_2 "Trigger event with id*"
expect_output "Received trigger from \"hypnotoad\""
expect_output " EventId { m_value: 42 }"
expect_output "Received trigger from \"brainslug\""
expect_output " EventId { m_value: 13 }"

show_test_passed
