[build]
rustdocflags = ["-D", "warnings"]

[env]
RUST_TEST_THREADS = "1"
RUST_BACKTRACE = "1"

[target.debug]
rustflags = ["-Z", "sanitizer=address"]
profiler = true

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-args=/STACK:8388608"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "link-args=/STACK:8388608"]

[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "link-args=-Wl,--stack,8388608"]

[target.aarch64-pc-windows-gnullvm]
rustflags = ["-C", "link-args=-Wl,--stack,8388608"]
