// automatically generated by the FlatBuffers compiler, do not modify
// @generated

extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod robot {

extern crate alloc;

// struct Timestamp, aligned to 4
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Timestamp(pub [u8; 8]);
impl Default for Timestamp { 
  fn default() -> Self { 
    Self([0; 8])
  }
}
impl ::core::fmt::Debug for Timestamp {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    f.debug_struct("Timestamp")
      .field("seconds", &self.seconds())
      .field("nanoseconds", &self.nanoseconds())
      .finish()
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Timestamp {}
impl<'a> ::flatbuffers::Follow<'a> for Timestamp {
  type Inner = &'a Timestamp;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { <&'a Timestamp>::follow(buf, loc) }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for &'a Timestamp {
  type Inner = &'a Timestamp;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { ::flatbuffers::follow_cast_ref::<Timestamp>(buf, loc) }
  }
}
impl<'b> ::flatbuffers::Push for Timestamp {
    type Output = Timestamp;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = unsafe { ::core::slice::from_raw_parts(self as *const Timestamp as *const u8, <Self as ::flatbuffers::Push>::size()) };
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> ::flatbuffers::PushAlignment {
        ::flatbuffers::PushAlignment::new(4)
    }
}

impl<'a> ::flatbuffers::Verifiable for Timestamp {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Timestamp {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    seconds: i32,
    nanoseconds: u32,
  ) -> Self {
    let mut s = Self([0; 8]);
    s.set_seconds(seconds);
    s.set_nanoseconds(nanoseconds);
    s
  }

  pub fn seconds(&self) -> i32 {
    let mut mem = ::core::mem::MaybeUninit::<<i32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<i32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_seconds(&mut self, x: i32) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        ::core::mem::size_of::<<i32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn nanoseconds(&self) -> u32 {
    let mut mem = ::core::mem::MaybeUninit::<<u32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[4..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_nanoseconds(&mut self, x: u32) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[4..].as_mut_ptr(),
        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

}

pub enum JointReadingsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct JointReadings<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for JointReadings<'a> {
  type Inner = JointReadings<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> JointReadings<'a> {
  pub const VT_CAPTURED_AT: ::flatbuffers::VOffsetT = 4;
  pub const VT_FRAME: ::flatbuffers::VOffsetT = 6;
  pub const VT_JOINTS: ::flatbuffers::VOffsetT = 8;
  pub const VT_ANGLES: ::flatbuffers::VOffsetT = 10;
  pub const VT_SPEEDS: ::flatbuffers::VOffsetT = 12;
  pub const VT_TORQUES: ::flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    JointReadings { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args JointReadingsArgs<'args>
  ) -> ::flatbuffers::WIPOffset<JointReadings<'bldr>> {
    let mut builder = JointReadingsBuilder::new(_fbb);
    if let Some(x) = args.torques { builder.add_torques(x); }
    if let Some(x) = args.speeds { builder.add_speeds(x); }
    if let Some(x) = args.angles { builder.add_angles(x); }
    if let Some(x) = args.joints { builder.add_joints(x); }
    if let Some(x) = args.frame { builder.add_frame(x); }
    if let Some(x) = args.captured_at { builder.add_captured_at(x); }
    builder.finish()
  }


  #[inline]
  pub fn captured_at(&self) -> &'a Timestamp {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Timestamp>(JointReadings::VT_CAPTURED_AT, None).unwrap()}
  }
  #[inline]
  pub fn frame(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(JointReadings::VT_FRAME, None).unwrap()}
  }
  #[inline]
  pub fn joints(&self) -> ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>(JointReadings::VT_JOINTS, None).unwrap()}
  }
  #[inline]
  pub fn angles(&self) -> ::flatbuffers::Vector<'a, f64> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, f64>>>(JointReadings::VT_ANGLES, None).unwrap()}
  }
  #[inline]
  pub fn speeds(&self) -> ::flatbuffers::Vector<'a, f64> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, f64>>>(JointReadings::VT_SPEEDS, None).unwrap()}
  }
  #[inline]
  pub fn torques(&self) -> ::flatbuffers::Vector<'a, f64> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, f64>>>(JointReadings::VT_TORQUES, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for JointReadings<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<Timestamp>("captured_at", Self::VT_CAPTURED_AT, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("frame", Self::VT_FRAME, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<&'_ str>>>>("joints", Self::VT_JOINTS, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, f64>>>("angles", Self::VT_ANGLES, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, f64>>>("speeds", Self::VT_SPEEDS, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, f64>>>("torques", Self::VT_TORQUES, true)?
     .finish();
    Ok(())
  }
}
pub struct JointReadingsArgs<'a> {
    pub captured_at: Option<&'a Timestamp>,
    pub frame: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub joints: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>,
    pub angles: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, f64>>>,
    pub speeds: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, f64>>>,
    pub torques: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, f64>>>,
}
impl<'a> Default for JointReadingsArgs<'a> {
  #[inline]
  fn default() -> Self {
    JointReadingsArgs {
      captured_at: None, // required field
      frame: None, // required field
      joints: None, // required field
      angles: None, // required field
      speeds: None, // required field
      torques: None, // required field
    }
  }
}

pub struct JointReadingsBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> JointReadingsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_captured_at(&mut self, captured_at: &Timestamp) {
    self.fbb_.push_slot_always::<&Timestamp>(JointReadings::VT_CAPTURED_AT, captured_at);
  }
  #[inline]
  pub fn add_frame(&mut self, frame: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(JointReadings::VT_FRAME, frame);
  }
  #[inline]
  pub fn add_joints(&mut self, joints: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(JointReadings::VT_JOINTS, joints);
  }
  #[inline]
  pub fn add_angles(&mut self, angles: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(JointReadings::VT_ANGLES, angles);
  }
  #[inline]
  pub fn add_speeds(&mut self, speeds: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(JointReadings::VT_SPEEDS, speeds);
  }
  #[inline]
  pub fn add_torques(&mut self, torques: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(JointReadings::VT_TORQUES, torques);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> JointReadingsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    JointReadingsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<JointReadings<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, JointReadings::VT_CAPTURED_AT,"captured_at");
    self.fbb_.required(o, JointReadings::VT_FRAME,"frame");
    self.fbb_.required(o, JointReadings::VT_JOINTS,"joints");
    self.fbb_.required(o, JointReadings::VT_ANGLES,"angles");
    self.fbb_.required(o, JointReadings::VT_SPEEDS,"speeds");
    self.fbb_.required(o, JointReadings::VT_TORQUES,"torques");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for JointReadings<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("JointReadings");
      ds.field("captured_at", &self.captured_at());
      ds.field("frame", &self.frame());
      ds.field("joints", &self.joints());
      ds.field("angles", &self.angles());
      ds.field("speeds", &self.speeds());
      ds.field("torques", &self.torques());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `JointReadings`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_joint_readings_unchecked`.
pub fn root_as_joint_readings(buf: &[u8]) -> Result<JointReadings<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<JointReadings>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `JointReadings` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_joint_readings_unchecked`.
pub fn size_prefixed_root_as_joint_readings(buf: &[u8]) -> Result<JointReadings<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<JointReadings>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `JointReadings` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_joint_readings_unchecked`.
pub fn root_as_joint_readings_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<JointReadings<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<JointReadings<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `JointReadings` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_joint_readings_unchecked`.
pub fn size_prefixed_root_as_joint_readings_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<JointReadings<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<JointReadings<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a JointReadings and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `JointReadings`.
pub unsafe fn root_as_joint_readings_unchecked(buf: &[u8]) -> JointReadings<'_> {
  unsafe { ::flatbuffers::root_unchecked::<JointReadings>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed JointReadings and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `JointReadings`.
pub unsafe fn size_prefixed_root_as_joint_readings_unchecked(buf: &[u8]) -> JointReadings<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<JointReadings>(buf) }
}
#[inline]
pub fn finish_joint_readings_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<JointReadings<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_joint_readings_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<JointReadings<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod robot

