name: 'Install iceoryx dependencies and clang-tidy'
runs:
  using: "composite"
  steps:
    - name: Install iceoryx dependencies and clang-tidy
      shell: bash
      run: |
        sudo wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main"
        sudo apt-get update
        sudo apt-get install -y libacl1-dev
        sudo apt-get install -y clang-format-19 clang-tidy-19 clang-tools-19 clang-19 lld
        sudo rm /usr/bin/clang
        sudo rm /usr/bin/clang++
        sudo rm /usr/bin/clang-tidy
        sudo rm /usr/bin/clang-format
        sudo ln -s /usr/bin/clang-19 /usr/bin/clang
        sudo ln -s /usr/bin/clang++-19 /usr/bin/clang++
        sudo ln -s /usr/bin/clang-tidy-19 /usr/bin/clang-tidy
        sudo ln -s /usr/bin/clang-format-19 /usr/bin/clang-format
        sudo ln -s /usr/bin/llvm-19 /usr/bin/llvm
        sudo ln -s /usr/bin/llvm-cov-19 /usr/bin/llvm-cov
        sudo ln -s /usr/bin/llvm-profdata-19 /usr/bin/llvm-profdata
