[package]
name = "iceoryx2-link-testing"
description = "iceoryx2: [internal] testing utilities for the link"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[features]
default = []
std = []
