# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

# pylint: skip-file
# mypy: ignore-errors

# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class UnboundedData(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UnboundedData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUnboundedData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # UnboundedData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UnboundedData
    def Text(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UnboundedData
    def Data(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0


def UnboundedDataStart(builder):
    builder.StartObject(2)


def Start(builder):
    UnboundedDataStart(builder)


def UnboundedDataAddText(builder, text):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(text), 0
    )


def AddText(builder, text):
    UnboundedDataAddText(builder, text)


def UnboundedDataAddData(builder, data):
    builder.PrependInt32Slot(1, data, 0)


def AddData(builder, data):
    UnboundedDataAddData(builder, data)


def UnboundedDataEnd(builder):
    return builder.EndObject()


def End(builder):
    return UnboundedDataEnd(builder)
