// NOLINTBEGIN

// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DATAPROPS_EXAMPLE_H_
#define FLATBUFFERS_GENERATED_DATAPROPS_EXAMPLE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 && FLATBUFFERS_VERSION_MINOR == 12 && FLATBUFFERS_VERSION_REVISION == 19,
              "Non-compatible flatbuffers version included");

namespace Example {

struct DataProps;
struct DataPropsBuilder;

struct DataProps FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef DataPropsBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_RECEIVED_ENTRIES_LEN = 4
    };
    uint64_t received_entries_len() const {
        return GetField<uint64_t>(VT_RECEIVED_ENTRIES_LEN, 0);
    }
    template <bool B = false>
    bool Verify(::flatbuffers::VerifierTemplate<B>& verifier) const {
        return VerifyTableStart(verifier) && VerifyField<uint64_t>(verifier, VT_RECEIVED_ENTRIES_LEN, 8)
               && verifier.EndTable();
    }
};

struct DataPropsBuilder {
    typedef DataProps Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_received_entries_len(uint64_t received_entries_len) {
        fbb_.AddElement<uint64_t>(DataProps::VT_RECEIVED_ENTRIES_LEN, received_entries_len, 0);
    }
    explicit DataPropsBuilder(::flatbuffers::FlatBufferBuilder& _fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<DataProps> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<DataProps>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<DataProps> CreateDataProps(::flatbuffers::FlatBufferBuilder& _fbb,
                                                        uint64_t received_entries_len = 0) {
    DataPropsBuilder builder_(_fbb);
    builder_.add_received_entries_len(received_entries_len);
    return builder_.Finish();
}

inline const Example::DataProps* GetDataProps(const void* buf) {
    return ::flatbuffers::GetRoot<Example::DataProps>(buf);
}

inline const Example::DataProps* GetSizePrefixedDataProps(const void* buf) {
    return ::flatbuffers::GetSizePrefixedRoot<Example::DataProps>(buf);
}

template <bool B = false>
inline bool VerifyDataPropsBuffer(::flatbuffers::VerifierTemplate<B>& verifier) {
    return verifier.template VerifyBuffer<Example::DataProps>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedDataPropsBuffer(::flatbuffers::VerifierTemplate<B>& verifier) {
    return verifier.template VerifySizePrefixedBuffer<Example::DataProps>(nullptr);
}

inline void FinishDataPropsBuffer(::flatbuffers::FlatBufferBuilder& fbb,
                                  ::flatbuffers::Offset<Example::DataProps> root) {
    fbb.Finish(root);
}

inline void FinishSizePrefixedDataPropsBuffer(::flatbuffers::FlatBufferBuilder& fbb,
                                              ::flatbuffers::Offset<Example::DataProps> root) {
    fbb.FinishSizePrefixed(root);
}

} // namespace Example

#endif // FLATBUFFERS_GENERATED_DATAPROPS_EXAMPLE_H_

// NOLINTEND
