#!/usr/bin/expect
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

#### Common Setup

set REPO_ROOT [exec git rev-parse --show-toplevel]
cd ${REPO_ROOT}

source ${REPO_ROOT}/internal/end-to-end-testing/common.exp

#### Test Setup

exec cargo build --manifest-path integrations/ros2/Cargo.toml \
    --bin iox2-link-gateway-ros2 2>@1
exec cargo build --manifest-path integrations/ros2/Cargo.toml \
    -p iceoryx2-integrations-ros2-examples --examples 2>@1

#### Test

set timeout 30

set env(IOX2_LOG_LEVEL) trace
spawn cargo run --manifest-path integrations/ros2/Cargo.toml \
    --bin iox2-link-gateway-ros2 -- \
    --allow /cmd_vel \
    --translator PlainStruct --ros-header --monitor
set id_gateway $spawn_id
drain_output $id_gateway
unset env(IOX2_LOG_LEVEL)

expect_output_from $id_gateway "Gateway started"

spawn cargo run --manifest-path integrations/ros2/Cargo.toml \
    --example plain_struct_prefix_mapping_subscriber
set id_subscriber $spawn_id

spawn ros2 topic pub -r 5 /cmd_vel geometry_msgs/msg/Twist "{linear: {x: 0.5}}"
set id_publisher $spawn_id

expect_output_from $id_gateway "Opened PublishSubscribe bridge of \"ros2://topics/cmd_vel\""
expect_output_from $id_gateway "Relayed PublishSubscribe bridge of \"ros2://topics/cmd_vel\""

#### Test Assertion

expect_output_from $id_subscriber "x: 0.5"

#### Shutdown

send -i $id_publisher $SIGINT
expect -i $id_publisher eof

send -i $id_subscriber $SIGINT
expect -i $id_subscriber eof

send -i $id_gateway $SIGINT
expect_output_from $id_gateway "Gateway stopped"
expect -i $id_gateway eof

show_test_passed
