#!/usr/bin/expect
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

#### Common Setup

set REPO_ROOT [exec git rev-parse --show-toplevel]
cd ${REPO_ROOT}

source ${REPO_ROOT}/internal/end-to-end-testing/common.exp

#### Test Setup

set timeout 10

#### Test

spawn cargo run --bin iox2-config -- explain
set id_iox2_config $spawn_id

#### Test Assertion

expect_output_from $id_iox2_config "== Global =="
expect_output_from $id_iox2_config "== Global: Node =="
expect_output_from $id_iox2_config "== Global: Service =="
expect_output_from $id_iox2_config "== Global: Service Creation Timeout =="
expect_output_from $id_iox2_config "== Defaults: Publish Subscribe Messaging Pattern =="
expect_output_from $id_iox2_config "== Defaults: Event Messaging Pattern =="
expect_output_from $id_iox2_config "== Defaults: Request Response Messaging Pattern =="
expect_output_from $id_iox2_config "== Defaults: Blackboard Messaging Pattern =="

show_test_passed
