#!/usr/bin/expect
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

#### Common Setup

set REPO_ROOT [exec git rev-parse --show-toplevel]
cd ${REPO_ROOT}

source ${REPO_ROOT}/internal/end-to-end-testing/common.exp

#### Test Setup

set timeout 10

#### Test

spawn cargo run --bin iox2-config -- show system
set id_iox2_config $spawn_id

#### Test Assertion

expect_output_from $id_iox2_config "posix system configuration"
expect_output_from $id_iox2_config "system info"
expect_output_from $id_iox2_config "limit"
expect_output_from $id_iox2_config "options"
expect_output_from $id_iox2_config "features"
expect_output_from $id_iox2_config "process resource limits"

show_test_passed
