#!/usr/bin/expect
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

#### Common Setup

set REPO_ROOT [exec git rev-parse --show-toplevel]
cd ${REPO_ROOT}

source examples/cross-language-end-to-end-tests/common.exp

#### Test Setup

set timeout 10

spawn target/ff/cc/build/examples/cxx/event_based_communication/example_cxx_event_based_communication_publisher
set id_publisher $spawn_id

spawn target/ff/cc/build/examples/cxx/event_based_communication/example_cxx_event_based_communication_subscriber

#### Test Assertion

expect_output_from $id_publisher "send message*"
expect_output "received: 2"

show_test_passed
