[package]
name = "iceoryx2-integrations-zenoh-link-tunnel-cli"
description = "iceoryx2-integrations: command line interface of the tunnel over zenoh"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[[bin]]
name = "iox2-link-tunnel-zenoh"
path = "src/main.rs"

