#!/usr/bin/expect
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

#### Common Setup

set REPO_ROOT [exec git rev-parse --show-toplevel]
cd ${REPO_ROOT}

source ${REPO_ROOT}/internal/end-to-end-testing/common.exp

#### Test Setup

set timeout 10

spawn cargo run --example request_response_with_events_server
set id_server $spawn_id
expect_output_from $id_server "Server ready to receive requests!"

# run two client to verify each client gets only one notification
spawn cargo run --example request_response_with_events_client
set id_client1 $spawn_id
spawn cargo run --example request_response_with_events_client
set id_client2 $spawn_id

#### Test Assertion
expect_output_from $id_client1 "send request 2"
expect_output_from $id_client1 "number of received notifications from server: 1"
expect_output_from $id_client1 "received response"
expect_output_from $id_client2 "send request 2"
expect_output_from $id_client2 "number of received notifications from server: 1"
expect_output_from $id_client2 "received response"

show_test_passed
