#!/usr/bin/expect
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

#### Common Setup

set REPO_ROOT [exec git rev-parse --show-toplevel]
cd ${REPO_ROOT}

source ${REPO_ROOT}/iceoryx2-testing/end-to-end-testing/common.exp

#### Test Setup

set timeout 10

#### Test

spawn cargo run --bin iox2-service discovery --detailed
set id_iox2_discovery $spawn_id

sleep 1

spawn cargo run --example publish_subscribe_subscriber
set id_subscriber $spawn_id

sleep 1
send -i $id_subscriber $SIGINT
expect -i $id_subscriber eof

#### Test Assertion

expect_output_from $id_iox2_discovery "Discovering Services (rate: 100ms)"
expect_output_from $id_iox2_discovery "Added"
expect_output_from $id_iox2_discovery "service_id"
expect_output_from $id_iox2_discovery "service_name"
expect_output_from $id_iox2_discovery "pattern"
expect_output_from $id_iox2_discovery "nodes"
expect_output_from $id_iox2_discovery "Removed"
expect_output_from $id_iox2_discovery "service_id"
expect_output_from $id_iox2_discovery "service_name"
expect_output_from $id_iox2_discovery "pattern"
expect_output_from $id_iox2_discovery "nodes"

show_test_passed
