#!/usr/bin/expect
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

#### Common Setup

set REPO_ROOT [exec git rev-parse --show-toplevel]
cd ${REPO_ROOT}

source ${REPO_ROOT}/internal/end-to-end-testing/common.exp

#### Test Setup

set timeout 30

#### Test

spawn cargo run --bin iox2-service discovery
set id_discovery $spawn_id
expect_output_from $id_discovery {Discovering Services}

spawn cargo run --example publish_subscribe_subscriber
set id_subscriber $spawn_id
expect_output_from $id_subscriber {Subscriber ready to receive data!}
expect_output_from $id_discovery {Added(PublishSubscribe("My/Funk/ServiceName"))}

send -i $id_subscriber $SIGINT
expect -i $id_subscriber eof
expect_output_from $id_discovery {Removed(PublishSubscribe("My/Funk/ServiceName"))}

show_test_passed
