#!/usr/bin/expect
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

#### Common Setup

set REPO_ROOT [exec git rev-parse --show-toplevel]
cd ${REPO_ROOT}

source ${REPO_ROOT}/internal/end-to-end-testing/common.exp

#### Test Setup

set timeout 10

#### Test

# Spawn a process that creates a node
spawn cargo run --example publish_subscribe_subscriber
set id_subscriber $spawn_id

# List nodes to get the node id
set list_output [exec cargo run --bin iox2-node -- list 2>@1]

if {[regexp {id: \("([a-f0-9]+)"\)} $list_output -> node_id]} {
    puts "Extracted node ID: $node_id"
} else {
    handle_test_failure "Failed to extract node ID from output"
}

# Use the node id to get details
spawn cargo run --bin iox2-node -- details $node_id
set id_iox2_node $spawn_id

#### Test Assertion

expect_output_from $id_iox2_node "state"
expect_output_from $id_iox2_node "id"
expect_output_from $id_iox2_node "pid"
expect_output_from $id_iox2_node "executable"
expect_output_from $id_iox2_node "name"
expect_output_from $id_iox2_node "config"

show_test_passed
