// Copyright (c) 2026 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Apache Software License 2.0 which is available at
// https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
// which is available at https://opensource.org/licenses/MIT.
//
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! An adapter implementation over ROS 2, for gateways between `iceoryx2`
//! and ROS 2.
//!
//! Each [`Ros2Adapter`] holds one ROS 2 node, through which the gateway
//! joins the graph like any other ROS 2 application. It speaks `rcl`
//! through [r2r_rcl](https://docs.rs/r2r_rcl), so it runs on whatever RMW
//! the installation provides.
//!
//! * The topics of the graph are the endpoints. A [`TopicDescription`]
//!   carries a topic's name, QoS profile and message type, taken from the
//!   discovered publishers and subscriptions.
//! * The gateway's own endpoints on a topic are a publisher and a
//!   subscription matching the description's QoS. Messages are taken in their
//!   serialized form straight into a loaned sample, with the message info
//!   alongside as a [`RosHeader`](ros_header::RosHeader).
//! * [`PrefixMapping`] maps a service in the form `ros2://topics/NAMESPACE/TOPIC`
//!   to the topic `/NAMESPACE/TOPIC`. A best-guess QoS is derived from the
//!   service description. Only recommended for prototyping.
//! * [`StaticMapping`] maps services and topics through a table defined in
//!   a configuration. Recommended for proper deployments.
//! * [`PassthroughTranslator`] applies no translation, so incoming CDR bytes
//!   are written directly into `iceoryx2` samples, and likewise, outgoing
//!   bytes must be CDR bytes. `iceoryx2` applications must (de)serialize the
//!   bytes themselves before use.
//! * [`PlainStructTranslator`] is only suitable for payload types that are the
//!   plain C struct generated by rosidl. Uses the [`CdrTranscoder`] to
//!   (de)serialize to CDR bytes at the boundary.
//! * Both translators mirror a topic with the [`MirroredHeader`] they are
//!   configured with which is empty by default. The message info only reaches
//!   services when configured to be [`MirroredHeader::RosHeader`].
//! * The [`Ros2Adapter`] implements [`iceoryx2_link_backend::Reactive`]
//!   and signals the gateway to wake up whenever the graph changes or a
//!   message arrives.

#![deny(unsafe_code)]

pub mod adapter;
pub mod config;
pub mod endpoint_description;
#[allow(unsafe_code)]
pub mod endpoints;
pub mod mapping;
pub mod qos;
pub mod ros_header;
pub mod testing;
#[allow(unsafe_code)]
pub mod translator;

#[allow(unsafe_code)]
pub(crate) mod rcl;
#[allow(unsafe_code)]
pub(crate) mod typesupport;

pub use adapter::Ros2Adapter;
pub use config::{Config, TopicName, TypeName};
pub use endpoint_description::{TopicDescription, TopicSettings, TopicTypes};
pub use endpoints::PublishSubscribeEndpoints;
pub use iceoryx2_link_backend::AllowList;
pub use mapping::{PrefixMapping, StaticMapping};
pub use qos::QosProfile;
pub use translator::{CdrTranscoder, MirroredHeader, PassthroughTranslator, PlainStructTranslator};

/// The name of the ROS 2 node representing the gateway.
#[allow(unsafe_code)]
const NODE_NAME: rcl::NodeName =
    unsafe { rcl::NodeName::from_c_str_static_unchecked(c"iceoryx2_gateway") };

/// The reason a string failed ROS 2 name validation.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub enum NameError {
    /// The name is empty where a name is required.
    Empty,
    /// A token is empty or contains characters outside `[A-Za-z0-9_]`, or
    /// starts with a digit.
    InvalidToken,
    /// A namespace does not start with `/`.
    NoLeadingSlash,
}

impl core::fmt::Display for NameError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "NameError::{self:?}")
    }
}

impl core::error::Error for NameError {}
