name: Reusable workflow for no_std

on:
  workflow_call:
jobs:
  x86_64_nostd:
    strategy:
      matrix:
        os: [ubuntu-latest]
        toolchain: [stable]
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # version v7.0.1

      - name: Install just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # version: v4.0.0

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # version: v1
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: armv7r-none-eabihf, x86_64-unknown-linux-gnu
          components: rust-src

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@fc920bf0ec8de6ee65d409111f7ec508035751ba # version: v0.0.11

      - name: Set caching env vars on non-Windows
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

      - name: Prepare Linux
        run: |
          internal/scripts/ci_prepare_ubuntu.sh
          uname -a

      - name: Build sdk (no_std)
        run: |
          rustc --version
          just build sdk +${{ matrix.toolchain }} --no_std

      - name: Test sdk (no_std)
        run: |
          rustc --version
          just test sdk +${{ matrix.toolchain }} --no_std

      - name: Build bare-metal examples (no_std)
        run: cd examples/nostd/bare-metal/rust && cargo build --examples && cd -

      - name: Build posix examples (no_std)
        run: cd examples/nostd/posix/rust && cargo build --examples && cd -
