name: Reusable workflow for C++ Vocabulary Types

on:
  workflow_call:
jobs:
  x86_64_cxx_binding_vocabulary_types_variations:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # version v7.0.1

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # version: v1
        with:
          toolchain: stable

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@fc920bf0ec8de6ee65d409111f7ec508035751ba # version: v0.0.11

      - name: Set caching env vars on non-Windows
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

      - name: Prepare Linux
        run: |
          internal/scripts/ci_prepare_ubuntu.sh
          uname -a

      - name: Get CPU count
        id: cpu
        uses: ./.github/actions/cpu-count

      - name: Build iceoryx2-ffi-c
        run: cargo build --package iceoryx2-ffi-c --profile dev-fast-build

      - name: Build build and test iceoryx2 C++ bindings with C++23
        run: |
          cmake -S . \
                -B target/ff/cc/build \
                -DBUILD_EXAMPLES=ON \
                -DBUILD_TESTING=ON \
                -DRUST_BUILD_ARTIFACT_PATH=$(pwd)/target/dev-fast-build \
                -DIOX2_CXX_STD_VERSION=23 \
                -DIOX2_BB_CXX_CONFIG_USE_STD_EXPECTED=OFF \
                -DIOX2_BB_CXX_CONFIG_USE_STD_OPTIONAL=OFF \
                -DCMAKE_C_COMPILER_LAUNCHER=sccache \
                -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
          cmake --build target/ff/cc/build --parallel ${{ steps.cpu.outputs.count }}
          cmake --install target/ff/cc/build --prefix target/ff/cc/install

          target/ff/cc/build/tests/iceoryx2-bb-cxx-tests
          target/ff/cc/build/tests/iceoryx2-cxx-tests

          cmake -S examples/cxx \
                -B target/ff/cc/out-of-tree \
                -DCMAKE_PREFIX_PATH=${{ github.workspace }}/target/ff/cc/install \
                -DCMAKE_C_COMPILER_LAUNCHER=sccache \
                -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
          cmake --build target/ff/cc/out-of-tree --parallel ${{ steps.cpu.outputs.count }}

          rm -rf target/ff/cc

      - name: Build and test iceoryx2 C++ bindings with std::expected
        run: |
          cmake -S . \
                -B target/ff/cc/build \
                -DBUILD_EXAMPLES=ON \
                -DBUILD_TESTING=ON \
                -DRUST_BUILD_ARTIFACT_PATH=$(pwd)/target/dev-fast-build \
                -DIOX2_BB_CXX_CONFIG_USE_STD_EXPECTED=ON \
                -DIOX2_BB_CXX_CONFIG_USE_STD_OPTIONAL=OFF \
                -DCMAKE_C_COMPILER_LAUNCHER=sccache \
                -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
          cmake --build target/ff/cc/build --parallel ${{ steps.cpu.outputs.count }}
          cmake --install target/ff/cc/build --prefix target/ff/cc/install

          target/ff/cc/build/tests/iceoryx2-bb-cxx-tests
          target/ff/cc/build/tests/iceoryx2-cxx-tests

          cmake -S examples/cxx \
                -B target/ff/cc/out-of-tree \
                -DCMAKE_PREFIX_PATH=${{ github.workspace }}/target/ff/cc/install \
                -DCMAKE_C_COMPILER_LAUNCHER=sccache \
                -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
          cmake --build target/ff/cc/out-of-tree --parallel ${{ steps.cpu.outputs.count }}

          rm -rf target/ff/cc

      - name: Build and test iceoryx2 C++ bindings with std::optional
        run: |
          cmake -S . \
                -B target/ff/cc/build \
                -DBUILD_EXAMPLES=ON \
                -DBUILD_TESTING=ON \
                -DRUST_BUILD_ARTIFACT_PATH=$(pwd)/target/dev-fast-build \
                -DIOX2_BB_CXX_CONFIG_USE_STD_EXPECTED=OFF \
                -DIOX2_BB_CXX_CONFIG_USE_STD_OPTIONAL=ON \
                -DCMAKE_C_COMPILER_LAUNCHER=sccache \
                -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
          cmake --build target/ff/cc/build --parallel ${{ steps.cpu.outputs.count }}
          cmake --install target/ff/cc/build --prefix target/ff/cc/install

          target/ff/cc/build/tests/iceoryx2-bb-cxx-tests
          target/ff/cc/build/tests/iceoryx2-cxx-tests

          cmake -S examples/cxx \
                -B target/ff/cc/out-of-tree \
                -DCMAKE_PREFIX_PATH=${{ github.workspace }}/target/ff/cc/install \
                -DCMAKE_C_COMPILER_LAUNCHER=sccache \
                -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
          cmake --build target/ff/cc/out-of-tree --parallel ${{ steps.cpu.outputs.count }}

          rm -rf target/ff/cc

      - name: Build and test iceoryx2 C++ bindings with std::expected and std::optional
        run: |
          cmake -S . \
                -B target/ff/cc/build \
                -DBUILD_EXAMPLES=ON \
                -DBUILD_TESTING=ON \
                -DRUST_BUILD_ARTIFACT_PATH=$(pwd)/target/dev-fast-build \
                -DIOX2_BB_CXX_CONFIG_USE_STD_EXPECTED=ON \
                -DIOX2_BB_CXX_CONFIG_USE_STD_OPTIONAL=ON \
                -DCMAKE_C_COMPILER_LAUNCHER=sccache \
                -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
          cmake --build target/ff/cc/build --parallel ${{ steps.cpu.outputs.count }}
          cmake --install target/ff/cc/build --prefix target/ff/cc/install

          target/ff/cc/build/tests/iceoryx2-bb-cxx-tests
          target/ff/cc/build/tests/iceoryx2-cxx-tests

          cmake -S examples/cxx \
                -B target/ff/cc/out-of-tree \
                -DCMAKE_PREFIX_PATH=${{ github.workspace }}/target/ff/cc/install \
                -DCMAKE_C_COMPILER_LAUNCHER=sccache \
                -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
          cmake --build target/ff/cc/out-of-tree --parallel ${{ steps.cpu.outputs.count }}

          rm -rf target/ff/cc

      - name: Build and test iceoryx2 C++ bindings with custom vocabulary types
        run: |
          cmake -S examples/cxx/custom_vocabulary_types  -B target/ff/cc/custom_vocabulary_types
          cmake --build target/ff/cc/custom_vocabulary_types
          cmake --install target/ff/cc/custom_vocabulary_types --prefix target/ff/cc/install

          cmake -S . \
                -B target/ff/cc/build \
                -DBUILD_EXAMPLES=ON \
                -DBUILD_TESTING=ON \
                -DRUST_BUILD_ARTIFACT_PATH=$(pwd)/target/dev-fast-build \
                -DIOX2_BB_CXX_CONFIG_USE_CUSTOM_VOCABULARY_TYPES=ON \
                -DIOX2_BB_CXX_CONFIG_CUSTOM_VOCABULARY_TYPES_CMAKE_TARGET="custom-vocabulary-types" \
                -DCMAKE_PREFIX_PATH=${{ github.workspace }}/target/ff/cc/install \
                -DCMAKE_C_COMPILER_LAUNCHER=sccache \
                -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
          cmake --build target/ff/cc/build --parallel ${{ steps.cpu.outputs.count }}
          cmake --install target/ff/cc/build --prefix target/ff/cc/install

          target/ff/cc/build/tests/iceoryx2-bb-cxx-tests
          target/ff/cc/build/tests/iceoryx2-cxx-tests

          cmake -S examples/cxx \
                -B target/ff/cc/out-of-tree \
                -DCMAKE_PREFIX_PATH=${{ github.workspace }}/target/ff/cc/install \
                -DCMAKE_C_COMPILER_LAUNCHER=sccache \
                -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
          cmake --build target/ff/cc/out-of-tree --parallel ${{ steps.cpu.outputs.count }}

          rm -rf target/ff/cc
