name: Reusable workflow for code coverage

on:
  workflow_call:

jobs:
  coverage:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # version v7.0.1

      - name: Install dependencies
        uses: ./.github/actions/install-iceoryx-deps-and-clang

      - name: Create test users and groups
        run: |
          sudo useradd testuser1
          sudo useradd testuser2
          sudo groupadd testgroup1
          sudo groupadd testgroup2

      - name: Install just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # version: v4.0.0

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # version: v1
        with:
          toolchain: 1.92.0
          components: llvm-tools

      - name: Download artifact cargo-nextest
        uses: ./.github/actions/download-cached-rust-tool
        with:
          artifact-bin-name: cargo-nextest
          artifact-upload-name: ubuntu-latest-cargo-nextest

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@fc920bf0ec8de6ee65d409111f7ec508035751ba # version: v0.0.11
        with:
          version: "v0.16.0" # upgrade once sccache is fixed: https://github.com/eclipse-iceoryx/iceoryx2/issues/809#issuecomment-5264837759

      - name: Set caching env vars on non-Windows
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

      - name: Setup gcovr
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # version: v7.0.0
        with:
          python-version: "3.13"
      - run: pip install gcovr==8.4

      - name: Download artifact grcov
        uses: ./.github/actions/download-cached-rust-tool
        with:
          artifact-bin-name: grcov
          artifact-upload-name: ${{ runner.os }}-grcov

      - name: Save disk space
        uses: ./.github/actions/save-disk-space
        with:
          mode: "remove-unneeded-software-from-runner"

      - name: Generate coverage profile
        run: just coverage generate-profile

      - name: Generate coverage report for html artifacts
        run: just coverage generate-report --html

      - name: Archive coverage-html artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # version: v7.0.1
        with:
          name: coverage-html
          path: target/ff/coverage/html/*
          retention-days: 90

      - name: Generate coverage report for Codecov
        run: just coverage generate-report --lcov

      - name: Upload Rust coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # version: v7.0.0
        with:
          files: target/ff/coverage/lcov/iceoryx2_lcov_rust.info
          name: iceoryx2
          flags: Rust
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload C++ coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # version: v7.0.0
        with:
          files: target/ff/coverage/lcov/iceoryx2_lcov_cpp.info
          name: iceoryx2
          flags: CPP
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
