// Copyright (c) 2026 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Apache Software License 2.0 which is available at
// https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
// which is available at https://opensource.org/licenses/MIT.
//
// SPDX-License-Identifier: Apache-2.0 OR MIT

use iceoryx2::prelude::*;
use rosidl_runtime_rs::{Message, RmwMessage};

/// The service payload is a byte slice holding the CDR-serialized message.
/// The type name is taken from the IDL-generated struct to match the
/// ROS side.
#[derive(Debug, Clone, Copy)]
#[repr(transparent)]
pub struct StdMsgStringByte(pub u8);

unsafe impl ZeroCopySend for StdMsgStringByte {
    unsafe fn type_name() -> &'static str {
        <<std_msgs::msg::String as Message>::RmwMsg as RmwMessage>::TYPE_NAME
    }
}

/// Byte view of a CDR payload slice.
pub fn as_bytes(payload: &[StdMsgStringByte]) -> &[u8] {
    // SAFETY: StdMsgStringByte is #[repr(transparent)] over u8, so length and
    // alignment carry over.
    unsafe { core::slice::from_raw_parts(payload.as_ptr().cast::<u8>(), payload.len()) }
}

/// Shared-memory payload for `geometry_msgs/msg/Twist`.
///
/// The `#[repr(C)]` `rmw` struct generated by `rosidl_generator_rs`,
/// with [`ZeroCopySend`] implemented so it can be used in an iceoryx2 service.
#[derive(Debug, Default, Clone)]
#[repr(transparent)]
pub struct Twist(pub geometry_msgs::msg::rmw::Twist);

unsafe impl ZeroCopySend for Twist {
    unsafe fn type_name() -> &'static str {
        <<geometry_msgs::msg::Twist as Message>::RmwMsg as RmwMessage>::TYPE_NAME
    }
}
